module Evergreen.Migrate.V102 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Evergreen.V102.LiveBook.DataSet
import Evergreen.V102.LiveBook.Types
import Evergreen.V102.Types
import Evergreen.V102.User
import Evergreen.V98.LiveBook.DataSet
import Evergreen.V98.LiveBook.Types
import Evergreen.V98.Types
import Evergreen.V98.User
import Lamdera.Migrations exposing (..)
import List


frontendModel : Evergreen.V98.Types.FrontendModel -> ModelMigration Evergreen.V102.Types.FrontendModel Evergreen.V102.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V98.Types.BackendModel -> ModelMigration Evergreen.V102.Types.BackendModel Evergreen.V102.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V98.Types.FrontendMsg -> MsgMigration Evergreen.V102.Types.FrontendMsg Evergreen.V102.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V98.Types.ToBackend -> MsgMigration Evergreen.V102.Types.ToBackend Evergreen.V102.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V98.Types.BackendMsg -> MsgMigration Evergreen.V102.Types.BackendMsg Evergreen.V102.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V98.Types.ToFrontend -> MsgMigration Evergreen.V102.Types.ToFrontend Evergreen.V102.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_LiveBook_DataSet_DataSet : Evergreen.V98.LiveBook.DataSet.DataSet -> Evergreen.V102.LiveBook.DataSet.DataSet
migrate_LiveBook_DataSet_DataSet old =
    old


migrate_LiveBook_DataSet_DataSetMetaData : Evergreen.V98.LiveBook.DataSet.DataSetMetaData -> Evergreen.V102.LiveBook.DataSet.DataSetMetaData
migrate_LiveBook_DataSet_DataSetMetaData old =
    old


migrate_LiveBook_Types_Book : Evergreen.V98.LiveBook.Types.Book -> Evergreen.V102.LiveBook.Types.Book
migrate_LiveBook_Types_Book old =
    { id = old.id
    , dirty = old.dirty
    , slug = old.slug
    , origin = old.origin
    , author = old.author
    , createdAt = old.createdAt
    , updatedAt = old.updatedAt
    , public = old.public
    , title = old.title
    , cells = old.cells |> List.map migrate_LiveBook_Types_Cell
    , currentIndex = old.currentIndex
    , initialStateString = old.initialStateString
    , stateExpression = old.stateExpression
    , stateBindings = old.stateBindings
    , fastTickInterval = old.fastTickInterval
    , stopExpressionString = old.stopExpressionString
    }


migrate_LiveBook_Types_Cell : Evergreen.V98.LiveBook.Types.Cell -> Evergreen.V102.LiveBook.Types.Cell
migrate_LiveBook_Types_Cell old =
    { index = old.index
    , text = old.text
    , bindings = old.bindings
    , expression = old.expression
    , value = old.value |> migrate_LiveBook_Types_CellValue
    , cellState = old.cellState |> migrate_LiveBook_Types_CellState
    , locked = old.locked
    }


migrate_LiveBook_Types_CellState : Evergreen.V98.LiveBook.Types.CellState -> Evergreen.V102.LiveBook.Types.CellState
migrate_LiveBook_Types_CellState old =
    case old of
        Evergreen.V98.LiveBook.Types.CSEdit ->
            Evergreen.V102.LiveBook.Types.CSEdit

        Evergreen.V98.LiveBook.Types.CSView ->
            Evergreen.V102.LiveBook.Types.CSView


migrate_LiveBook_Types_CellValue : Evergreen.V98.LiveBook.Types.CellValue -> Evergreen.V102.LiveBook.Types.CellValue
migrate_LiveBook_Types_CellValue old =
    case old of
        Evergreen.V98.LiveBook.Types.CVNone ->
            Evergreen.V102.LiveBook.Types.CVNone

        Evergreen.V98.LiveBook.Types.CVString p0 ->
            Evergreen.V102.LiveBook.Types.CVString p0

        Evergreen.V98.LiveBook.Types.CVVisual p0 p1 ->
            Evergreen.V102.LiveBook.Types.CVVisual (p0 |> migrate_LiveBook_Types_VisualType) p1

        Evergreen.V98.LiveBook.Types.CVPlot2D p0 p1 ->
            Evergreen.V102.LiveBook.Types.CVPlot2D p0 p1


migrate_LiveBook_Types_VisualType : Evergreen.V98.LiveBook.Types.VisualType -> Evergreen.V102.LiveBook.Types.VisualType
migrate_LiveBook_Types_VisualType old =
    case old of
        Evergreen.V98.LiveBook.Types.VTChart ->
            Evergreen.V102.LiveBook.Types.VTChart

        Evergreen.V98.LiveBook.Types.VTSvg ->
            Evergreen.V102.LiveBook.Types.VTSvg

        Evergreen.V98.LiveBook.Types.VTImage ->
            Evergreen.V102.LiveBook.Types.VTImage


migrate_Types_DataSetDescription : Evergreen.V98.Types.DataSetDescription -> Evergreen.V102.Types.DataSetDescription
migrate_Types_DataSetDescription old =
    case old of
        Evergreen.V98.Types.PublicDatasets ->
            Evergreen.V102.Types.PublicDatasets

        Evergreen.V98.Types.UserDatasets p0 ->
            Evergreen.V102.Types.UserDatasets p0


migrate_Types_Message : Evergreen.V98.Types.Message -> Evergreen.V102.Types.Message
migrate_Types_Message old =
    { txt = old.txt
    , status = old.status |> migrate_Types_MessageStatus
    }


migrate_Types_MessageStatus : Evergreen.V98.Types.MessageStatus -> Evergreen.V102.Types.MessageStatus
migrate_Types_MessageStatus old =
    case old of
        Evergreen.V98.Types.MSWhite ->
            Evergreen.V102.Types.MSWhite

        Evergreen.V98.Types.MSYellow ->
            Evergreen.V102.Types.MSYellow

        Evergreen.V98.Types.MSGreen ->
            Evergreen.V102.Types.MSGreen

        Evergreen.V98.Types.MSRed ->
            Evergreen.V102.Types.MSRed


migrate_Types_ToBackend : Evergreen.V98.Types.ToBackend -> Evergreen.V102.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V98.Types.NoOpToBackend ->
            Evergreen.V102.Types.NoOpToBackend

        Evergreen.V98.Types.GetRandomSeed ->
            Evergreen.V102.Types.GetRandomSeed

        Evergreen.V98.Types.RunTask ->
            Evergreen.V102.Types.RunTask

        Evergreen.V98.Types.SendUsers ->
            Evergreen.V102.Types.SendUsers

        Evergreen.V98.Types.DeleteDataSet p0 ->
            Evergreen.V102.Types.DeleteDataSet (p0 |> migrate_LiveBook_DataSet_DataSetMetaData)

        Evergreen.V98.Types.SaveDataSet p0 ->
            Evergreen.V102.Types.SaveDataSet (p0 |> migrate_LiveBook_DataSet_DataSetMetaData)

        Evergreen.V98.Types.GetListOfDataSets p0 ->
            Evergreen.V102.Types.GetListOfDataSets (p0 |> migrate_Types_DataSetDescription)

        Evergreen.V98.Types.CreateDataSet p0 ->
            Evergreen.V102.Types.CreateDataSet (p0 |> migrate_LiveBook_DataSet_DataSet)

        Evergreen.V98.Types.GetData p0 p1 p2 ->
            Evergreen.V102.Types.GetData p0 p1 p2

        Evergreen.V98.Types.GetDataSetForDownload p0 ->
            Evergreen.V102.Types.GetDataSetForDownload p0

        Evergreen.V98.Types.CreateNotebook p0 p1 ->
            Evergreen.V102.Types.CreateNotebook p0 p1

        Evergreen.V98.Types.ImportNewBook p0 p1 ->
            Evergreen.V102.Types.ImportNewBook p0 (p1 |> migrate_LiveBook_Types_Book)

        Evergreen.V98.Types.SaveNotebook p0 ->
            Evergreen.V102.Types.SaveNotebook (p0 |> migrate_LiveBook_Types_Book)

        Evergreen.V98.Types.DeleteNotebook p0 ->
            Evergreen.V102.Types.DeleteNotebook (p0 |> migrate_LiveBook_Types_Book)

        Evergreen.V98.Types.GetClonedNotebook p0 p1 ->
            Evergreen.V102.Types.GetClonedNotebook p0 p1

        Evergreen.V98.Types.GetPulledNotebook p0 p1 p2 p3 ->
            Evergreen.V102.Types.GetPulledNotebook p0 p1 p2 p3

        Evergreen.V98.Types.UpdateSlugDict p0 ->
            Evergreen.V102.Types.UpdateSlugDict (p0 |> migrate_LiveBook_Types_Book)

        Evergreen.V98.Types.GetUsersNotebooks p0 ->
            Evergreen.V102.Types.GetUsersNotebooks p0

        Evergreen.V98.Types.GetPublicNotebooks p0 ->
            Evergreen.V102.Types.GetPublicNotebooks p0

        Evergreen.V98.Types.SignUpBE p0 p1 p2 ->
            Evergreen.V102.Types.SignUpBE p0 p1 p2

        Evergreen.V98.Types.SignInBEDev ->
            Evergreen.V102.Types.SignInBEDev

        Evergreen.V98.Types.SignInBE p0 p1 ->
            Evergreen.V102.Types.SignInBE p0 p1

        Evergreen.V98.Types.SignOutBE p0 ->
            Evergreen.V102.Types.SignOutBE p0

        Evergreen.V98.Types.UpdateUserWith p0 ->
            Evergreen.V102.Types.UpdateUserWith (p0 |> migrate_User_User)


migrate_Types_ToFrontend : Evergreen.V98.Types.ToFrontend -> Evergreen.V102.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V98.Types.NoOpToFrontend ->
            Evergreen.V102.Types.NoOpToFrontend

        Evergreen.V98.Types.MessageReceived p0 ->
            Evergreen.V102.Types.MessageReceived (p0 |> migrate_Types_Message)

        Evergreen.V98.Types.GotRandomSeed p0 ->
            Evergreen.V102.Types.GotRandomSeed p0

        Evergreen.V98.Types.GotUsers p0 ->
            Evergreen.V102.Types.GotUsers p0

        Evergreen.V98.Types.GotListOfPublicDataSets p0 ->
            Evergreen.V102.Types.GotListOfPublicDataSets p0

        Evergreen.V98.Types.GotListOfPrivateDataSets p0 ->
            Evergreen.V102.Types.GotListOfPrivateDataSets p0

        Evergreen.V98.Types.GotData p0 p1 p2 ->
            Evergreen.V102.Types.GotData p0 p1 (p2 |> migrate_LiveBook_DataSet_DataSet)

        Evergreen.V98.Types.GotDataForDownload p0 ->
            Evergreen.V102.Types.GotDataForDownload (p0 |> migrate_LiveBook_DataSet_DataSet)

        Evergreen.V98.Types.GotNotebook p0 ->
            Evergreen.V102.Types.GotNotebook (p0 |> migrate_LiveBook_Types_Book)

        Evergreen.V98.Types.GotNotebooks p0 ->
            Evergreen.V102.Types.GotNotebooks (p0 |> List.map migrate_LiveBook_Types_Book)

        Evergreen.V98.Types.SendMessage p0 ->
            Evergreen.V102.Types.SendMessage p0

        Evergreen.V98.Types.UserSignedIn p0 p1 ->
            Evergreen.V102.Types.UserSignedIn (p0 |> migrate_User_User) p1

        Evergreen.V98.Types.SendUser p0 ->
            Evergreen.V102.Types.SendUser (p0 |> migrate_User_User)


migrate_User_User : Evergreen.V98.User.User -> Evergreen.V102.User.User
migrate_User_User old =
    old
