module Evergreen.Migrate.V110 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Array
import Dict
import Evergreen.V104.FastDict
import Evergreen.V104.Internal
import Evergreen.V104.LiveBook.DataSet
import Evergreen.V104.LiveBook.State
import Evergreen.V104.LiveBook.Types
import Evergreen.V104.Types
import Evergreen.V104.Value
import Evergreen.V110.FastDict
import Evergreen.V110.Internal
import Evergreen.V110.LiveBook.DataSet
import Evergreen.V110.LiveBook.State
import Evergreen.V110.LiveBook.Types
import Evergreen.V110.Types
import Evergreen.V110.Value
import Lamdera.Migrations exposing (..)
import List


frontendModel : Evergreen.V104.Types.FrontendModel -> ModelMigration Evergreen.V110.Types.FrontendModel Evergreen.V110.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V104.Types.BackendModel -> ModelMigration Evergreen.V110.Types.BackendModel Evergreen.V110.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V104.Types.FrontendMsg -> MsgMigration Evergreen.V110.Types.FrontendMsg Evergreen.V110.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V104.Types.ToBackend -> MsgMigration Evergreen.V110.Types.ToBackend Evergreen.V110.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V104.Types.BackendMsg -> MsgMigration Evergreen.V110.Types.BackendMsg Evergreen.V110.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V104.Types.ToFrontend -> MsgMigration Evergreen.V110.Types.ToFrontend Evergreen.V110.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V104.Types.FrontendModel -> Evergreen.V110.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , url = old.url
    , message = old.message
    , messages = old.messages |> List.map migrate_Types_Message
    , appState = old.appState |> migrate_Types_AppState
    , appMode = old.appMode |> migrate_Types_AppMode
    , currentTime = old.currentTime
    , tickCount = old.tickCount
    , fastTickInterval = old.fastTickInterval
    , clockState = old.clockState |> migrate_Types_ClockState
    , pressedKeys = old.pressedKeys
    , randomSeed = old.randomSeed
    , randomProbabilities = old.randomProbabilities
    , probabilityVectorLength = old.probabilityVectorLength
    , users = old.users
    , inputName = old.inputName
    , inputIdentifier = old.inputIdentifier
    , inputAuthor = old.inputAuthor
    , inputDescription = old.inputDescription
    , inputComments = old.inputComments
    , inputData = old.inputData
    , inputInitialStateValue = old.inputInitialStateValue
    , inputFastTickInterval = old.inputFastTickInterval
    , inputStateExpression = old.inputStateExpression
    , inputStateBindings = old.inputStateBindings
    , inputStopExpression = old.inputStopExpression
    , publicDataSetMetaDataList = old.publicDataSetMetaDataList
    , privateDataSetMetaDataList = old.privateDataSetMetaDataList
    , kvDict = old.kvDict
    , books = old.books |> List.map migrate_LiveBook_Types_Book
    , currentBook = old.currentBook |> migrate_LiveBook_Types_Book
    , cellContent = old.cellContent
    , currentCellIndex = old.currentCellIndex
    , cloneReference = old.cloneReference
    , deleteNotebookState = old.deleteNotebookState |> migrate_Types_DeleteNotebookState
    , showNotebooks = old.showNotebooks |> migrate_Types_ShowNotebooks
    , valueDict = old.valueDict |> Dict.map (\k -> migrate_Value_Value)
    , nextStateRecord = old.nextStateRecord
    , state = old.state |> migrate_LiveBook_State_MState
    , signupState = old.signupState |> migrate_Types_SignupState
    , currentUser = old.currentUser
    , inputUsername = old.inputUsername
    , inputSignupUsername = old.inputSignupUsername
    , inputEmail = old.inputEmail
    , inputRealname = old.inputRealname
    , inputPassword = old.inputPassword
    , inputPasswordAgain = old.inputPasswordAgain
    , inputTitle = old.inputTitle
    , windowWidth = old.windowWidth
    , windowHeight = old.windowHeight
    , popupState = old.popupState |> migrate_Types_PopupState
    , showEditor = old.showEditor
    }


migrate_FastDict_Dict : (k_old -> k_new) -> (v_old -> v_new) -> Evergreen.V104.FastDict.Dict k_old v_old -> Evergreen.V110.FastDict.Dict k_new v_new
migrate_FastDict_Dict migrate_k migrate_v old =
    old |> migrate_Internal_InternalDict migrate_k migrate_v


migrate_Internal_InnerDict : (k_old -> k_new) -> (v_old -> v_new) -> Evergreen.V104.Internal.InnerDict k_old v_old -> Evergreen.V110.Internal.InnerDict k_new v_new
migrate_Internal_InnerDict migrate_k migrate_v old =
    case old of
        Evergreen.V104.Internal.InnerNode p0 p1 p2 p3 p4 ->
            Evergreen.V110.Internal.InnerNode (p0 |> migrate_Internal_NColor)
                (p1 |> migrate_k)
                (p2 |> migrate_v)
                (p3 |> migrate_Internal_InnerDict migrate_k migrate_v)
                (p4 |> migrate_Internal_InnerDict migrate_k migrate_v)

        Evergreen.V104.Internal.Leaf ->
            Evergreen.V110.Internal.Leaf


migrate_Internal_InternalDict : (k_old -> k_new) -> (v_old -> v_new) -> Evergreen.V104.Internal.InternalDict k_old v_old -> Evergreen.V110.Internal.InternalDict k_new v_new
migrate_Internal_InternalDict migrate_k migrate_v old =
    case old of
        Evergreen.V104.Internal.Dict p0 p1 ->
            Evergreen.V110.Internal.Dict p0
                (p1 |> migrate_Internal_InnerDict migrate_k migrate_v)


migrate_Internal_NColor : Evergreen.V104.Internal.NColor -> Evergreen.V110.Internal.NColor
migrate_Internal_NColor old =
    case old of
        Evergreen.V104.Internal.Red ->
            Evergreen.V110.Internal.Red

        Evergreen.V104.Internal.Black ->
            Evergreen.V110.Internal.Black


migrate_LiveBook_DataSet_DataSetMetaData : Evergreen.V104.LiveBook.DataSet.DataSetMetaData -> Evergreen.V110.LiveBook.DataSet.DataSetMetaData
migrate_LiveBook_DataSet_DataSetMetaData old =
    old


migrate_LiveBook_State_MState : Evergreen.V104.LiveBook.State.MState -> Evergreen.V110.LiveBook.State.MState
migrate_LiveBook_State_MState old =
    { currentValue = old.currentValue |> migrate_Value_Value
    , values = old.values |> List.map migrate_Value_Value
    , initialValue = old.initialValue |> migrate_Value_Value
    , keep = 1000
    , probabilities = old.probabilities
    , ticks = old.ticks
    , expression = old.expression
    , bindings = old.bindings
    , fastTickInterval = old.fastTickInterval
    , stopExpressionString = old.stopExpressionString
    }


migrate_LiveBook_Types_Book : Evergreen.V104.LiveBook.Types.Book -> Evergreen.V110.LiveBook.Types.Book
migrate_LiveBook_Types_Book old =
    { id = old.id
    , dirty = old.dirty
    , slug = old.slug
    , origin = old.origin
    , author = old.author
    , createdAt = old.createdAt
    , updatedAt = old.updatedAt
    , public = old.public
    , title = old.title
    , cells = old.cells |> List.map migrate_LiveBook_Types_Cell
    , currentIndex = old.currentIndex
    , initialStateString = old.initialStateString
    , stateExpression = old.stateExpression
    , stateBindings = old.stateBindings
    , fastTickInterval = old.fastTickInterval
    , stopExpressionString = old.stopExpressionString
    }


migrate_LiveBook_Types_Cell : Evergreen.V104.LiveBook.Types.Cell -> Evergreen.V110.LiveBook.Types.Cell
migrate_LiveBook_Types_Cell old =
    { index = old.index
    , text = old.text
    , bindings = old.bindings
    , expression = old.expression
    , value = old.value |> migrate_LiveBook_Types_CellValue
    , cellState = old.cellState |> migrate_LiveBook_Types_CellState
    , locked = old.locked
    }


migrate_LiveBook_Types_CellState : Evergreen.V104.LiveBook.Types.CellState -> Evergreen.V110.LiveBook.Types.CellState
migrate_LiveBook_Types_CellState old =
    case old of
        Evergreen.V104.LiveBook.Types.CSEdit ->
            Evergreen.V110.LiveBook.Types.CSEdit

        Evergreen.V104.LiveBook.Types.CSView ->
            Evergreen.V110.LiveBook.Types.CSView


migrate_LiveBook_Types_CellValue : Evergreen.V104.LiveBook.Types.CellValue -> Evergreen.V110.LiveBook.Types.CellValue
migrate_LiveBook_Types_CellValue old =
    case old of
        Evergreen.V104.LiveBook.Types.CVNone ->
            Evergreen.V110.LiveBook.Types.CVNone

        Evergreen.V104.LiveBook.Types.CVString p0 ->
            Evergreen.V110.LiveBook.Types.CVString p0

        Evergreen.V104.LiveBook.Types.CVVisual p0 p1 ->
            Evergreen.V110.LiveBook.Types.CVVisual (p0 |> migrate_LiveBook_Types_VisualType) p1

        Evergreen.V104.LiveBook.Types.CVPlot2D p0 p1 ->
            Evergreen.V110.LiveBook.Types.CVPlot2D p0 p1


migrate_LiveBook_Types_VisualType : Evergreen.V104.LiveBook.Types.VisualType -> Evergreen.V110.LiveBook.Types.VisualType
migrate_LiveBook_Types_VisualType old =
    case old of
        Evergreen.V104.LiveBook.Types.VTChart ->
            Evergreen.V110.LiveBook.Types.VTChart

        Evergreen.V104.LiveBook.Types.VTSvg ->
            Evergreen.V110.LiveBook.Types.VTSvg

        Evergreen.V104.LiveBook.Types.VTImage ->
            Evergreen.V110.LiveBook.Types.VTImage


migrate_Types_AppMode : Evergreen.V104.Types.AppMode -> Evergreen.V110.Types.AppMode
migrate_Types_AppMode old =
    case old of
        Evergreen.V104.Types.AMWorking ->
            Evergreen.V110.Types.AMWorking

        Evergreen.V104.Types.AMEditTitle ->
            Evergreen.V110.Types.AMEditTitle


migrate_Types_AppState : Evergreen.V104.Types.AppState -> Evergreen.V110.Types.AppState
migrate_Types_AppState old =
    case old of
        Evergreen.V104.Types.Loading ->
            Evergreen.V110.Types.Loading

        Evergreen.V104.Types.Loaded ->
            Evergreen.V110.Types.Loaded


migrate_Types_ClockState : Evergreen.V104.Types.ClockState -> Evergreen.V110.Types.ClockState
migrate_Types_ClockState old =
    case old of
        Evergreen.V104.Types.ClockRunning ->
            Evergreen.V110.Types.ClockRunning

        Evergreen.V104.Types.ClockStopped ->
            Evergreen.V110.Types.ClockStopped

        Evergreen.V104.Types.ClockPaused ->
            Evergreen.V110.Types.ClockPaused


migrate_Types_DeleteNotebookState : Evergreen.V104.Types.DeleteNotebookState -> Evergreen.V110.Types.DeleteNotebookState
migrate_Types_DeleteNotebookState old =
    case old of
        Evergreen.V104.Types.WaitingToDeleteNotebook ->
            Evergreen.V110.Types.WaitingToDeleteNotebook

        Evergreen.V104.Types.CanDeleteNotebook ->
            Evergreen.V110.Types.CanDeleteNotebook


migrate_Types_Message : Evergreen.V104.Types.Message -> Evergreen.V110.Types.Message
migrate_Types_Message old =
    { txt = old.txt
    , status = old.status |> migrate_Types_MessageStatus
    }


migrate_Types_MessageStatus : Evergreen.V104.Types.MessageStatus -> Evergreen.V110.Types.MessageStatus
migrate_Types_MessageStatus old =
    case old of
        Evergreen.V104.Types.MSWhite ->
            Evergreen.V110.Types.MSWhite

        Evergreen.V104.Types.MSYellow ->
            Evergreen.V110.Types.MSYellow

        Evergreen.V104.Types.MSGreen ->
            Evergreen.V110.Types.MSGreen

        Evergreen.V104.Types.MSRed ->
            Evergreen.V110.Types.MSRed


migrate_Types_PopupState : Evergreen.V104.Types.PopupState -> Evergreen.V110.Types.PopupState
migrate_Types_PopupState old =
    case old of
        Evergreen.V104.Types.NoPopup ->
            Evergreen.V110.Types.NoPopup

        Evergreen.V104.Types.AdminPopup ->
            Evergreen.V110.Types.AdminPopup

        Evergreen.V104.Types.ManualPopup ->
            Evergreen.V110.Types.ManualPopup

        Evergreen.V104.Types.NewDataSetPopup ->
            Evergreen.V110.Types.NewDataSetPopup

        Evergreen.V104.Types.EditDataSetPopup p0 ->
            Evergreen.V110.Types.EditDataSetPopup (p0 |> migrate_LiveBook_DataSet_DataSetMetaData)

        Evergreen.V104.Types.SignUpPopup ->
            Evergreen.V110.Types.SignUpPopup

        Evergreen.V104.Types.NewNotebookPopup ->
            Evergreen.V110.Types.NewNotebookPopup

        Evergreen.V104.Types.StateEditorPopup ->
            Evergreen.V110.Types.StateEditorPopup

        Evergreen.V104.Types.ViewPublicDataSetsPopup ->
            Evergreen.V110.Types.ViewPublicDataSetsPopup

        Evergreen.V104.Types.ViewPrivateDataSetsPopup ->
            Evergreen.V110.Types.ViewPrivateDataSetsPopup


migrate_Types_ShowNotebooks : Evergreen.V104.Types.ShowNotebooks -> Evergreen.V110.Types.ShowNotebooks
migrate_Types_ShowNotebooks old =
    case old of
        Evergreen.V104.Types.ShowUserNotebooks ->
            Evergreen.V110.Types.ShowUserNotebooks

        Evergreen.V104.Types.ShowPublicNotebooks ->
            Evergreen.V110.Types.ShowPublicNotebooks


migrate_Types_SignupState : Evergreen.V104.Types.SignupState -> Evergreen.V110.Types.SignupState
migrate_Types_SignupState old =
    case old of
        Evergreen.V104.Types.ShowSignUpForm ->
            Evergreen.V110.Types.ShowSignUpForm

        Evergreen.V104.Types.HideSignUpForm ->
            Evergreen.V110.Types.HideSignUpForm


migrate_Value_Env : Evergreen.V104.Value.Env -> Evergreen.V110.Value.Env
migrate_Value_Env old =
    { currentModule = old.currentModule
    , functions = old.functions |> migrate_FastDict_Dict identity (migrate_FastDict_Dict identity identity)
    , values = old.values |> migrate_Value_EnvValues
    , callStack = old.callStack
    }


migrate_Value_EnvValues : Evergreen.V104.Value.EnvValues -> Evergreen.V110.Value.EnvValues
migrate_Value_EnvValues old =
    old |> migrate_FastDict_Dict identity migrate_Value_Value


migrate_Value_Value : Evergreen.V104.Value.Value -> Evergreen.V110.Value.Value
migrate_Value_Value old =
    case old of
        Evergreen.V104.Value.String p0 ->
            Evergreen.V110.Value.String p0

        Evergreen.V104.Value.Int p0 ->
            Evergreen.V110.Value.Int p0

        Evergreen.V104.Value.Float p0 ->
            Evergreen.V110.Value.Float p0

        Evergreen.V104.Value.Char p0 ->
            Evergreen.V110.Value.Char p0

        Evergreen.V104.Value.Bool p0 ->
            Evergreen.V110.Value.Bool p0

        Evergreen.V104.Value.Unit ->
            Evergreen.V110.Value.Unit

        Evergreen.V104.Value.Tuple p0 p1 ->
            Evergreen.V110.Value.Tuple (p0 |> migrate_Value_Value)
                (p1 |> migrate_Value_Value)

        Evergreen.V104.Value.Triple p0 p1 p2 ->
            Evergreen.V110.Value.Triple (p0 |> migrate_Value_Value)
                (p1 |> migrate_Value_Value)
                (p2 |> migrate_Value_Value)

        Evergreen.V104.Value.Record p0 ->
            Evergreen.V110.Value.Record (p0 |> migrate_FastDict_Dict identity migrate_Value_Value)

        Evergreen.V104.Value.Custom p0 p1 ->
            Evergreen.V110.Value.Custom p0 (p1 |> List.map migrate_Value_Value)

        Evergreen.V104.Value.PartiallyApplied p0 p1 p2 p3 p4 ->
            Evergreen.V110.Value.PartiallyApplied (p0 |> migrate_Value_Env)
                (p1 |> List.map migrate_Value_Value)
                p2
                p3
                p4

        Evergreen.V104.Value.JsArray p0 ->
            Evergreen.V110.Value.JsArray (p0 |> Array.map migrate_Value_Value)

        Evergreen.V104.Value.List p0 ->
            Evergreen.V110.Value.List (p0 |> List.map migrate_Value_Value)
