module Evergreen.Migrate.V24 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V23.Authentication
import Evergreen.V23.Credentials
import Evergreen.V23.Types
import Evergreen.V23.User
import Evergreen.V24.Authentication
import Evergreen.V24.Credentials
import Evergreen.V24.Types
import Evergreen.V24.User
import Lamdera.Migrations exposing (..)
import List


frontendModel : Evergreen.V23.Types.FrontendModel -> ModelMigration Evergreen.V24.Types.FrontendModel Evergreen.V24.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V23.Types.BackendModel -> ModelMigration Evergreen.V24.Types.BackendModel Evergreen.V24.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V23.Types.FrontendMsg -> MsgMigration Evergreen.V24.Types.FrontendMsg Evergreen.V24.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V23.Types.ToBackend -> MsgMigration Evergreen.V24.Types.ToBackend Evergreen.V24.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V23.Types.BackendMsg -> MsgMigration Evergreen.V24.Types.BackendMsg Evergreen.V24.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V23.Types.ToFrontend -> MsgMigration Evergreen.V24.Types.ToFrontend Evergreen.V24.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_BackendModel : Evergreen.V23.Types.BackendModel -> Evergreen.V24.Types.BackendModel
migrate_Types_BackendModel old =
    { message = old.message
    , currentTime = old.currentTime
    , randomSeed = old.randomSeed
    , uuidCount = old.uuidCount
    , uuid = old.uuid
    , randomAtmosphericInt = old.randomAtmosphericInt
    , userToNoteBookDict = old.userToNoteBookDict |> migrate_Types_UserToNoteBookDict
    , slugDict = Dict.empty
    , authenticationDict = old.authenticationDict |> migrate_Authentication_AuthenticationDict
    }


migrate_Types_FrontendModel : Evergreen.V23.Types.FrontendModel -> Evergreen.V24.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , url = old.url
    , message = old.message
    , messages = old.messages |> List.map migrate_Types_Message
    , appState = old.appState |> migrate_Types_AppState
    , appMode = old.appMode |> migrate_Types_AppMode
    , currentTime = old.currentTime
    , pressedKeys = old.pressedKeys
    , users = old.users
    , books = old.books |> List.map migrate_Types_Book
    , currentBook = old.currentBook |> migrate_Types_Book
    , cellContent = old.cellContent
    , currentCellIndex = old.currentCellIndex
    , cloneReference = ""
    , signupState = old.signupState |> migrate_Types_SignupState
    , currentUser = old.currentUser
    , inputUsername = old.inputUsername
    , inputSignupUsername = old.inputSignupUsername
    , inputEmail = old.inputEmail
    , inputRealname = old.inputRealname
    , inputPassword = old.inputPassword
    , inputPasswordAgain = old.inputPasswordAgain
    , inputTitle = old.inputTitle
    , windowWidth = old.windowWidth
    , windowHeight = old.windowHeight
    , popupState = old.popupState |> migrate_Types_PopupState
    , showEditor = old.showEditor
    }


migrate_Authentication_AuthenticationDict : Evergreen.V23.Authentication.AuthenticationDict -> Evergreen.V24.Authentication.AuthenticationDict
migrate_Authentication_AuthenticationDict old =
    old |> Dict.map (\k -> migrate_Authentication_UserData)


migrate_Authentication_UserData : Evergreen.V23.Authentication.UserData -> Evergreen.V24.Authentication.UserData
migrate_Authentication_UserData old =
    { user = old.user |> migrate_User_User
    , credentials = old.credentials |> migrate_Credentials_Credentials
    }


migrate_Credentials_Credentials : Evergreen.V23.Credentials.Credentials -> Evergreen.V24.Credentials.Credentials
migrate_Credentials_Credentials old =
    case old of
        Evergreen.V23.Credentials.V1 p0 p1 ->
            Evergreen.V24.Credentials.V1 p0 p1


migrate_Types_AppMode : Evergreen.V23.Types.AppMode -> Evergreen.V24.Types.AppMode
migrate_Types_AppMode old =
    case old of
        Evergreen.V23.Types.AMWorking ->
            Evergreen.V24.Types.AMWorking

        Evergreen.V23.Types.AMEditTitle ->
            Evergreen.V24.Types.AMEditTitle


migrate_Types_AppState : Evergreen.V23.Types.AppState -> Evergreen.V24.Types.AppState
migrate_Types_AppState old =
    case old of
        Evergreen.V23.Types.Loading ->
            Evergreen.V24.Types.Loading

        Evergreen.V23.Types.Loaded ->
            Evergreen.V24.Types.Loaded


migrate_Types_Book : Evergreen.V23.Types.Book -> Evergreen.V24.Types.Book
migrate_Types_Book old =
    { id = old.id
    , dirty = old.dirty
    , slug = old.slug
    , author = old.author
    , createdAt = old.createdAt
    , updatedAt = old.updatedAt
    , public = old.public
    , title = old.title
    , cells = old.cells |> List.map migrate_Types_Cell
    , currentIndex = old.currentIndex
    }


migrate_Types_Cell : Evergreen.V23.Types.Cell -> Evergreen.V24.Types.Cell
migrate_Types_Cell old =
    { index = old.index
    , text = old.text
    , value = old.value
    , cellState = old.cellState |> migrate_Types_CellState
    }


migrate_Types_CellState : Evergreen.V23.Types.CellState -> Evergreen.V24.Types.CellState
migrate_Types_CellState old =
    case old of
        Evergreen.V23.Types.CSEdit ->
            Evergreen.V24.Types.CSEdit

        Evergreen.V23.Types.CSView ->
            Evergreen.V24.Types.CSView


migrate_Types_FrontendMsg : Evergreen.V23.Types.FrontendMsg -> Evergreen.V24.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V23.Types.UrlClicked p0 ->
            Evergreen.V24.Types.UrlClicked p0

        Evergreen.V23.Types.UrlChanged p0 ->
            Evergreen.V24.Types.UrlChanged p0

        Evergreen.V23.Types.NoOpFrontendMsg ->
            Evergreen.V24.Types.NoOpFrontendMsg

        Evergreen.V23.Types.FETick p0 ->
            Evergreen.V24.Types.FETick p0

        Evergreen.V23.Types.KeyboardMsg p0 ->
            Evergreen.V24.Types.KeyboardMsg p0

        Evergreen.V23.Types.NewCell p0 ->
            Evergreen.V24.Types.NewCell p0

        Evergreen.V23.Types.EditCell p0 ->
            Evergreen.V24.Types.EditCell p0

        Evergreen.V23.Types.ClearCell p0 ->
            Evergreen.V24.Types.ClearCell p0

        Evergreen.V23.Types.EvalCell p0 ->
            Evergreen.V24.Types.EvalCell p0

        Evergreen.V23.Types.InputElmCode p0 p1 ->
            Evergreen.V24.Types.InputElmCode p0 p1

        Evergreen.V23.Types.UpdateNotebookTitle ->
            Evergreen.V24.Types.UpdateNotebookTitle

        Evergreen.V23.Types.NewNotebook ->
            Evergreen.V24.Types.NewNotebook

        Evergreen.V23.Types.ChangeAppMode p0 ->
            Evergreen.V24.Types.ChangeAppMode (p0 |> migrate_Types_AppMode)

        Evergreen.V23.Types.TogglePublic ->
            Evergreen.V24.Types.TogglePublic

        Evergreen.V23.Types.SetCurrentNotebook p0 ->
            Evergreen.V24.Types.SetCurrentNotebook (p0 |> migrate_Types_Book)

        Evergreen.V23.Types.ChangePopup p0 ->
            Evergreen.V24.Types.ChangePopup (p0 |> migrate_Types_PopupState)

        Evergreen.V23.Types.GotViewport p0 ->
            Evergreen.V24.Types.GotViewport p0

        Evergreen.V23.Types.GotNewWindowDimensions p0 p1 ->
            Evergreen.V24.Types.GotNewWindowDimensions p0 p1

        Evergreen.V23.Types.SignUp ->
            Evergreen.V24.Types.SignUp

        Evergreen.V23.Types.SignIn ->
            Evergreen.V24.Types.SignIn

        Evergreen.V23.Types.SignOut ->
            Evergreen.V24.Types.SignOut

        Evergreen.V23.Types.SetSignupState p0 ->
            Evergreen.V24.Types.SetSignupState (p0 |> migrate_Types_SignupState)

        Evergreen.V23.Types.InputUsername p0 ->
            Evergreen.V24.Types.InputUsername p0

        Evergreen.V23.Types.InputSignupUsername p0 ->
            Evergreen.V24.Types.InputSignupUsername p0

        Evergreen.V23.Types.InputPassword p0 ->
            Evergreen.V24.Types.InputPassword p0

        Evergreen.V23.Types.InputPasswordAgain p0 ->
            Evergreen.V24.Types.InputPasswordAgain p0

        Evergreen.V23.Types.InputEmail p0 ->
            Evergreen.V24.Types.InputEmail p0

        Evergreen.V23.Types.InputTitle p0 ->
            Evergreen.V24.Types.InputTitle p0

        Evergreen.V23.Types.AdminRunTask ->
            Evergreen.V24.Types.AdminRunTask

        Evergreen.V23.Types.GetUsers ->
            Evergreen.V24.Types.GetUsers


migrate_Types_Message : Evergreen.V23.Types.Message -> Evergreen.V24.Types.Message
migrate_Types_Message old =
    { txt = old.txt
    , status = old.status |> migrate_Types_MessageStatus
    }


migrate_Types_MessageStatus : Evergreen.V23.Types.MessageStatus -> Evergreen.V24.Types.MessageStatus
migrate_Types_MessageStatus old =
    case old of
        Evergreen.V23.Types.MSWhite ->
            Evergreen.V24.Types.MSWhite

        Evergreen.V23.Types.MSYellow ->
            Evergreen.V24.Types.MSYellow

        Evergreen.V23.Types.MSGreen ->
            Evergreen.V24.Types.MSGreen

        Evergreen.V23.Types.MSRed ->
            Evergreen.V24.Types.MSRed


migrate_Types_NoteBookDict : Evergreen.V23.Types.NoteBookDict -> Evergreen.V24.Types.NoteBookDict
migrate_Types_NoteBookDict old =
    old |> Dict.map (\k -> migrate_Types_Book)


migrate_Types_PopupState : Evergreen.V23.Types.PopupState -> Evergreen.V24.Types.PopupState
migrate_Types_PopupState old =
    case old of
        Evergreen.V23.Types.NoPopup ->
            Evergreen.V24.Types.NoPopup

        Evergreen.V23.Types.AdminPopup ->
            Evergreen.V24.Types.AdminPopup

        Evergreen.V23.Types.SignUpPopup ->
            Evergreen.V24.Types.SignUpPopup

        Evergreen.V23.Types.NewNotebookPopup ->
            Evergreen.V24.Types.NewNotebookPopup


migrate_Types_SignupState : Evergreen.V23.Types.SignupState -> Evergreen.V24.Types.SignupState
migrate_Types_SignupState old =
    case old of
        Evergreen.V23.Types.ShowSignUpForm ->
            Evergreen.V24.Types.ShowSignUpForm

        Evergreen.V23.Types.HideSignUpForm ->
            Evergreen.V24.Types.HideSignUpForm


migrate_Types_ToBackend : Evergreen.V23.Types.ToBackend -> Evergreen.V24.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V23.Types.NoOpToBackend ->
            Evergreen.V24.Types.NoOpToBackend

        Evergreen.V23.Types.RunTask ->
            Evergreen.V24.Types.RunTask

        Evergreen.V23.Types.SendUsers ->
            Evergreen.V24.Types.SendUsers

        Evergreen.V23.Types.CreateNotebook p0 p1 ->
            Evergreen.V24.Types.CreateNotebook p0 p1

        Evergreen.V23.Types.SaveNotebook p0 ->
            Evergreen.V24.Types.SaveNotebook (p0 |> migrate_Types_Book)

        Evergreen.V23.Types.SignUpBE p0 p1 p2 ->
            Evergreen.V24.Types.SignUpBE p0 p1 p2

        Evergreen.V23.Types.SignInBEDev ->
            Evergreen.V24.Types.SignInBEDev

        Evergreen.V23.Types.SignInBE p0 p1 ->
            Evergreen.V24.Types.SignInBE p0 p1

        Evergreen.V23.Types.SignOutBE p0 ->
            Evergreen.V24.Types.SignOutBE p0

        Evergreen.V23.Types.UpdateUserWith p0 ->
            Evergreen.V24.Types.UpdateUserWith (p0 |> migrate_User_User)


migrate_Types_UserToNoteBookDict : Evergreen.V23.Types.UserToNoteBookDict -> Evergreen.V24.Types.UserToNoteBookDict
migrate_Types_UserToNoteBookDict old =
    old |> Dict.map (\k -> migrate_Types_NoteBookDict)


migrate_User_User : Evergreen.V23.User.User -> Evergreen.V24.User.User
migrate_User_User old =
    old
