module Evergreen.Migrate.V3 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V1.Authentication
import Evergreen.V1.Credentials
import Evergreen.V1.Types
import Evergreen.V1.User
import Evergreen.V3.Authentication
import Evergreen.V3.Credentials
import Evergreen.V3.Types
import Evergreen.V3.User
import Lamdera.Migrations exposing (..)
import List


frontendModel : Evergreen.V1.Types.FrontendModel -> ModelMigration Evergreen.V3.Types.FrontendModel Evergreen.V3.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V1.Types.BackendModel -> ModelMigration Evergreen.V3.Types.BackendModel Evergreen.V3.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V1.Types.FrontendMsg -> MsgMigration Evergreen.V3.Types.FrontendMsg Evergreen.V3.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V1.Types.ToBackend -> MsgMigration Evergreen.V3.Types.ToBackend Evergreen.V3.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V1.Types.BackendMsg -> MsgMigration Evergreen.V3.Types.BackendMsg Evergreen.V3.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V1.Types.ToFrontend -> MsgMigration Evergreen.V3.Types.ToFrontend Evergreen.V3.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V1.Types.BackendModel -> Evergreen.V3.Types.BackendModel
migrate_Types_BackendModel old =
    { message = old.message
    , currentTime = old.currentTime
    , randomSeed = old.randomSeed
    , uuidCount = old.uuidCount
    , uuid = old.uuid
    , randomAtmosphericInt = old.randomAtmosphericInt
    , dataSetLibrary = Dict.empty
    , userToNoteBookDict = old.userToNoteBookDict |> migrate_Types_UserToNoteBookDict
    , slugDict = old.slugDict
    , authenticationDict = old.authenticationDict |> migrate_Authentication_AuthenticationDict
    }


migrate_Types_FrontendModel : Evergreen.V1.Types.FrontendModel -> Evergreen.V3.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , url = old.url
    , message = old.message
    , messages = old.messages |> List.map migrate_Types_Message
    , appState = old.appState |> migrate_Types_AppState
    , appMode = old.appMode |> migrate_Types_AppMode
    , currentTime = old.currentTime
    , pressedKeys = old.pressedKeys
    , users = old.users
    , inputName = ""
    , inputAuthor = ""
    , inputDescription = ""
    , inputComments = ""
    , inputData = ""
    , kvDict = old.kvDict
    , books = old.books |> List.map migrate_Types_Book
    , currentBook = old.currentBook |> migrate_Types_Book
    , cellContent = old.cellContent
    , currentCellIndex = old.currentCellIndex
    , cloneReference = old.cloneReference
    , deleteNotebookState = old.deleteNotebookState |> migrate_Types_DeleteNotebookState
    , showNotebooks = old.showNotebooks |> migrate_Types_ShowNotebooks
    , signupState = old.signupState |> migrate_Types_SignupState
    , currentUser = old.currentUser
    , inputUsername = old.inputUsername
    , inputSignupUsername = old.inputSignupUsername
    , inputEmail = old.inputEmail
    , inputRealname = old.inputRealname
    , inputPassword = old.inputPassword
    , inputPasswordAgain = old.inputPasswordAgain
    , inputTitle = old.inputTitle
    , windowWidth = old.windowWidth
    , windowHeight = old.windowHeight
    , popupState = old.popupState |> migrate_Types_PopupState
    , showEditor = old.showEditor
    }


migrate_Authentication_AuthenticationDict : Evergreen.V1.Authentication.AuthenticationDict -> Evergreen.V3.Authentication.AuthenticationDict
migrate_Authentication_AuthenticationDict old =
    old |> Dict.map (\k -> migrate_Authentication_UserData)


migrate_Authentication_UserData : Evergreen.V1.Authentication.UserData -> Evergreen.V3.Authentication.UserData
migrate_Authentication_UserData old =
    { user = old.user |> migrate_User_User
    , credentials = old.credentials |> migrate_Credentials_Credentials
    }


migrate_Credentials_Credentials : Evergreen.V1.Credentials.Credentials -> Evergreen.V3.Credentials.Credentials
migrate_Credentials_Credentials old =
    case old of
        Evergreen.V1.Credentials.V1 p0 p1 ->
            Evergreen.V3.Credentials.V1 p0 p1


migrate_Types_AppMode : Evergreen.V1.Types.AppMode -> Evergreen.V3.Types.AppMode
migrate_Types_AppMode old =
    case old of
        Evergreen.V1.Types.AMWorking ->
            Evergreen.V3.Types.AMWorking

        Evergreen.V1.Types.AMEditTitle ->
            Evergreen.V3.Types.AMEditTitle


migrate_Types_AppState : Evergreen.V1.Types.AppState -> Evergreen.V3.Types.AppState
migrate_Types_AppState old =
    case old of
        Evergreen.V1.Types.Loading ->
            Evergreen.V3.Types.Loading

        Evergreen.V1.Types.Loaded ->
            Evergreen.V3.Types.Loaded


migrate_Types_Book : Evergreen.V1.Types.Book -> Evergreen.V3.Types.Book
migrate_Types_Book old =
    { id = old.id
    , dirty = old.dirty
    , slug = old.slug
    , origin = old.origin
    , author = old.author
    , createdAt = old.createdAt
    , updatedAt = old.updatedAt
    , public = old.public
    , title = old.title
    , cells = old.cells |> List.map migrate_Types_Cell
    , currentIndex = old.currentIndex
    }


migrate_Types_Cell : Evergreen.V1.Types.Cell -> Evergreen.V3.Types.Cell
migrate_Types_Cell old =
    { index = old.index
    , text = old.text
    , value = old.value |> migrate_Types_CellValue
    , cellState = old.cellState |> migrate_Types_CellState
    }


migrate_Types_CellState : Evergreen.V1.Types.CellState -> Evergreen.V3.Types.CellState
migrate_Types_CellState old =
    case old of
        Evergreen.V1.Types.CSEdit ->
            Evergreen.V3.Types.CSEdit

        Evergreen.V1.Types.CSView ->
            Evergreen.V3.Types.CSView


migrate_Types_CellValue : Evergreen.V1.Types.CellValue -> Evergreen.V3.Types.CellValue
migrate_Types_CellValue old =
    case old of
        Evergreen.V1.Types.CVNone ->
            Evergreen.V3.Types.CVNone

        Evergreen.V1.Types.CVString p0 ->
            Evergreen.V3.Types.CVString p0

        Evergreen.V1.Types.CVVisual p0 p1 ->
            Evergreen.V3.Types.CVVisual (p0 |> migrate_Types_VisualType) p1


migrate_Types_DeleteNotebookState : Evergreen.V1.Types.DeleteNotebookState -> Evergreen.V3.Types.DeleteNotebookState
migrate_Types_DeleteNotebookState old =
    case old of
        Evergreen.V1.Types.WaitingToDeleteNotebook ->
            Evergreen.V3.Types.WaitingToDeleteNotebook

        Evergreen.V1.Types.CanDeleteNotebook ->
            Evergreen.V3.Types.CanDeleteNotebook


migrate_Types_FrontendMsg : Evergreen.V1.Types.FrontendMsg -> Evergreen.V3.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V1.Types.UrlClicked p0 ->
            Evergreen.V3.Types.UrlClicked p0

        Evergreen.V1.Types.UrlChanged p0 ->
            Evergreen.V3.Types.UrlChanged p0

        Evergreen.V1.Types.NoOpFrontendMsg ->
            Evergreen.V3.Types.NoOpFrontendMsg

        Evergreen.V1.Types.FETick p0 ->
            Evergreen.V3.Types.FETick p0

        Evergreen.V1.Types.KeyboardMsg p0 ->
            Evergreen.V3.Types.KeyboardMsg p0

        Evergreen.V1.Types.StringDataRequested p0 p1 ->
            Evergreen.V3.Types.StringDataRequested p0 p1

        Evergreen.V1.Types.StringDataSelected p0 p1 p2 ->
            Evergreen.V3.Types.StringDataSelected p0 p1 p2

        Evergreen.V1.Types.StringDataLoaded p0 p1 p2 p3 ->
            Evergreen.V3.Types.StringDataLoaded p0 p1 p2 p3

        Evergreen.V1.Types.NewCell p0 ->
            Evergreen.V3.Types.NewCell p0

        Evergreen.V1.Types.DeleteCell p0 ->
            Evergreen.V3.Types.DeleteCell p0

        Evergreen.V1.Types.EditCell p0 ->
            Evergreen.V3.Types.EditCell p0

        Evergreen.V1.Types.ClearCell p0 ->
            Evergreen.V3.Types.ClearCell p0

        Evergreen.V1.Types.EvalCell p0 ->
            Evergreen.V3.Types.EvalCell p0

        Evergreen.V1.Types.InputElmCode p0 p1 ->
            Evergreen.V3.Types.InputElmCode p0 p1

        Evergreen.V1.Types.UpdateNotebookTitle ->
            Evergreen.V3.Types.UpdateNotebookTitle

        Evergreen.V1.Types.NewNotebook ->
            Evergreen.V3.Types.NewNotebook

        Evergreen.V1.Types.ProposeDeletingNotebook ->
            Evergreen.V3.Types.ProposeDeletingNotebook

        Evergreen.V1.Types.CancelDeleteNotebook ->
            Evergreen.V3.Types.CancelDeleteNotebook

        Evergreen.V1.Types.ChangeAppMode p0 ->
            Evergreen.V3.Types.ChangeAppMode (p0 |> migrate_Types_AppMode)

        Evergreen.V1.Types.TogglePublic ->
            Evergreen.V3.Types.TogglePublic

        Evergreen.V1.Types.ClearNotebookValues ->
            Evergreen.V3.Types.ClearNotebookValues

        Evergreen.V1.Types.SetCurrentNotebook p0 ->
            Evergreen.V3.Types.SetCurrentNotebook (p0 |> migrate_Types_Book)

        Evergreen.V1.Types.CloneNotebook ->
            Evergreen.V3.Types.CloneNotebook

        Evergreen.V1.Types.PullNotebook ->
            Evergreen.V3.Types.PullNotebook

        Evergreen.V1.Types.SetShowNotebooksState p0 ->
            Evergreen.V3.Types.SetShowNotebooksState (p0 |> migrate_Types_ShowNotebooks)

        Evergreen.V1.Types.ChangePopup p0 ->
            Evergreen.V3.Types.ChangePopup (p0 |> migrate_Types_PopupState)

        Evergreen.V1.Types.GotViewport p0 ->
            Evergreen.V3.Types.GotViewport p0

        Evergreen.V1.Types.GotNewWindowDimensions p0 p1 ->
            Evergreen.V3.Types.GotNewWindowDimensions p0 p1

        Evergreen.V1.Types.SignUp ->
            Evergreen.V3.Types.SignUp

        Evergreen.V1.Types.SignIn ->
            Evergreen.V3.Types.SignIn

        Evergreen.V1.Types.SignOut ->
            Evergreen.V3.Types.SignOut

        Evergreen.V1.Types.SetSignupState p0 ->
            Evergreen.V3.Types.SetSignupState (p0 |> migrate_Types_SignupState)

        Evergreen.V1.Types.InputUsername p0 ->
            Evergreen.V3.Types.InputUsername p0

        Evergreen.V1.Types.InputSignupUsername p0 ->
            Evergreen.V3.Types.InputSignupUsername p0

        Evergreen.V1.Types.InputPassword p0 ->
            Evergreen.V3.Types.InputPassword p0

        Evergreen.V1.Types.InputPasswordAgain p0 ->
            Evergreen.V3.Types.InputPasswordAgain p0

        Evergreen.V1.Types.InputEmail p0 ->
            Evergreen.V3.Types.InputEmail p0

        Evergreen.V1.Types.InputTitle p0 ->
            Evergreen.V3.Types.InputTitle p0

        Evergreen.V1.Types.InputCloneReference p0 ->
            Evergreen.V3.Types.InputCloneReference p0

        Evergreen.V1.Types.AdminRunTask ->
            Evergreen.V3.Types.AdminRunTask

        Evergreen.V1.Types.GetUsers ->
            Evergreen.V3.Types.GetUsers


migrate_Types_Message : Evergreen.V1.Types.Message -> Evergreen.V3.Types.Message
migrate_Types_Message old =
    { txt = old.txt
    , status = old.status |> migrate_Types_MessageStatus
    }


migrate_Types_MessageStatus : Evergreen.V1.Types.MessageStatus -> Evergreen.V3.Types.MessageStatus
migrate_Types_MessageStatus old =
    case old of
        Evergreen.V1.Types.MSWhite ->
            Evergreen.V3.Types.MSWhite

        Evergreen.V1.Types.MSYellow ->
            Evergreen.V3.Types.MSYellow

        Evergreen.V1.Types.MSGreen ->
            Evergreen.V3.Types.MSGreen

        Evergreen.V1.Types.MSRed ->
            Evergreen.V3.Types.MSRed


migrate_Types_NoteBookDict : Evergreen.V1.Types.NoteBookDict -> Evergreen.V3.Types.NoteBookDict
migrate_Types_NoteBookDict old =
    old |> Dict.map (\k -> migrate_Types_Book)


migrate_Types_PopupState : Evergreen.V1.Types.PopupState -> Evergreen.V3.Types.PopupState
migrate_Types_PopupState old =
    case old of
        Evergreen.V1.Types.NoPopup ->
            Evergreen.V3.Types.NoPopup

        Evergreen.V1.Types.AdminPopup ->
            Evergreen.V3.Types.AdminPopup

        Evergreen.V1.Types.ManualPopup ->
            Evergreen.V3.Types.ManualPopup

        Evergreen.V1.Types.SignUpPopup ->
            Evergreen.V3.Types.SignUpPopup

        Evergreen.V1.Types.NewNotebookPopup ->
            Evergreen.V3.Types.NewNotebookPopup


migrate_Types_ShowNotebooks : Evergreen.V1.Types.ShowNotebooks -> Evergreen.V3.Types.ShowNotebooks
migrate_Types_ShowNotebooks old =
    case old of
        Evergreen.V1.Types.ShowUserNotebooks ->
            Evergreen.V3.Types.ShowUserNotebooks

        Evergreen.V1.Types.ShowPublicNotebooks ->
            Evergreen.V3.Types.ShowPublicNotebooks


migrate_Types_SignupState : Evergreen.V1.Types.SignupState -> Evergreen.V3.Types.SignupState
migrate_Types_SignupState old =
    case old of
        Evergreen.V1.Types.ShowSignUpForm ->
            Evergreen.V3.Types.ShowSignUpForm

        Evergreen.V1.Types.HideSignUpForm ->
            Evergreen.V3.Types.HideSignUpForm


migrate_Types_ToBackend : Evergreen.V1.Types.ToBackend -> Evergreen.V3.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V1.Types.NoOpToBackend ->
            Evergreen.V3.Types.NoOpToBackend

        Evergreen.V1.Types.RunTask ->
            Evergreen.V3.Types.RunTask

        Evergreen.V1.Types.SendUsers ->
            Evergreen.V3.Types.SendUsers

        Evergreen.V1.Types.CreateNotebook p0 p1 ->
            Evergreen.V3.Types.CreateNotebook p0 p1

        Evergreen.V1.Types.SaveNotebook p0 ->
            Evergreen.V3.Types.SaveNotebook (p0 |> migrate_Types_Book)

        Evergreen.V1.Types.DeleteNotebook p0 ->
            Evergreen.V3.Types.DeleteNotebook (p0 |> migrate_Types_Book)

        Evergreen.V1.Types.GetClonedNotebook p0 p1 ->
            Evergreen.V3.Types.GetClonedNotebook p0 p1

        Evergreen.V1.Types.GetPulledNotebook p0 p1 p2 p3 ->
            Evergreen.V3.Types.GetPulledNotebook p0 p1 p2 p3

        Evergreen.V1.Types.UpdateSlugDict p0 ->
            Evergreen.V3.Types.UpdateSlugDict (p0 |> migrate_Types_Book)

        Evergreen.V1.Types.GetUsersNotebooks p0 ->
            Evergreen.V3.Types.GetUsersNotebooks p0

        Evergreen.V1.Types.GetPublicNotebooks p0 ->
            Evergreen.V3.Types.GetPublicNotebooks p0

        Evergreen.V1.Types.SignUpBE p0 p1 p2 ->
            Evergreen.V3.Types.SignUpBE p0 p1 p2

        Evergreen.V1.Types.SignInBEDev ->
            Evergreen.V3.Types.SignInBEDev

        Evergreen.V1.Types.SignInBE p0 p1 ->
            Evergreen.V3.Types.SignInBE p0 p1

        Evergreen.V1.Types.SignOutBE p0 ->
            Evergreen.V3.Types.SignOutBE p0

        Evergreen.V1.Types.UpdateUserWith p0 ->
            Evergreen.V3.Types.UpdateUserWith (p0 |> migrate_User_User)


migrate_Types_ToFrontend : Evergreen.V1.Types.ToFrontend -> Evergreen.V3.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V1.Types.NoOpToFrontend ->
            Evergreen.V3.Types.NoOpToFrontend

        Evergreen.V1.Types.MessageReceived p0 ->
            Evergreen.V3.Types.MessageReceived (p0 |> migrate_Types_Message)

        Evergreen.V1.Types.GotUsers p0 ->
            Evergreen.V3.Types.GotUsers p0

        Evergreen.V1.Types.GotNotebook p0 ->
            Evergreen.V3.Types.GotNotebook (p0 |> migrate_Types_Book)

        Evergreen.V1.Types.GotNotebooks p0 ->
            Evergreen.V3.Types.GotNotebooks (p0 |> List.map migrate_Types_Book)

        Evergreen.V1.Types.SendMessage p0 ->
            Evergreen.V3.Types.SendMessage p0

        Evergreen.V1.Types.UserSignedIn p0 p1 ->
            Evergreen.V3.Types.UserSignedIn (p0 |> migrate_User_User) p1

        Evergreen.V1.Types.SendUser p0 ->
            Evergreen.V3.Types.SendUser (p0 |> migrate_User_User)


migrate_Types_UserToNoteBookDict : Evergreen.V1.Types.UserToNoteBookDict -> Evergreen.V3.Types.UserToNoteBookDict
migrate_Types_UserToNoteBookDict old =
    old |> Dict.map (\k -> migrate_Types_NoteBookDict)


migrate_Types_VisualType : Evergreen.V1.Types.VisualType -> Evergreen.V3.Types.VisualType
migrate_Types_VisualType old =
    case old of
        Evergreen.V1.Types.VTChart ->
            Evergreen.V3.Types.VTChart

        Evergreen.V1.Types.VTImage ->
            Evergreen.V3.Types.VTImage


migrate_User_User : Evergreen.V1.User.User -> Evergreen.V3.User.User
migrate_User_User old =
    old
