module Evergreen.Migrate.V50 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Evergreen.V37.LiveBook.DataSet
import Evergreen.V37.LiveBook.Types
import Evergreen.V37.Types
import Evergreen.V50.LiveBook.DataSet
import Evergreen.V50.LiveBook.Types
import Evergreen.V50.Types
import Lamdera.Migrations exposing (..)
import List


frontendModel : Evergreen.V37.Types.FrontendModel -> ModelMigration Evergreen.V50.Types.FrontendModel Evergreen.V50.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V37.Types.BackendModel -> ModelMigration Evergreen.V50.Types.BackendModel Evergreen.V50.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V37.Types.FrontendMsg -> MsgMigration Evergreen.V50.Types.FrontendMsg Evergreen.V50.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V37.Types.ToBackend -> MsgMigration Evergreen.V50.Types.ToBackend Evergreen.V50.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V37.Types.BackendMsg -> MsgMigration Evergreen.V50.Types.BackendMsg Evergreen.V50.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V37.Types.ToFrontend -> MsgMigration Evergreen.V50.Types.ToFrontend Evergreen.V50.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V37.Types.FrontendModel -> Evergreen.V50.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , url = old.url
    , message = old.message
    , messages = old.messages |> List.map migrate_Types_Message
    , appState = old.appState |> migrate_Types_AppState
    , appMode = old.appMode |> migrate_Types_AppMode
    , currentTime = old.currentTime
    , pressedKeys = old.pressedKeys
    , users = old.users
    , inputName = old.inputName
    , inputIdentifier = ""
    , inputAuthor = old.inputAuthor
    , inputDescription = old.inputDescription
    , inputComments = old.inputComments
    , inputData = old.inputData
    , publicDataSetMetaDataList = old.publicDataSetMetaDataList
    , privateDataSetMetaDataList = old.privateDataSetMetaDataList
    , kvDict = old.kvDict
    , books = old.books |> List.map migrate_LiveBook_Types_Book
    , currentBook = old.currentBook |> migrate_LiveBook_Types_Book
    , cellContent = old.cellContent
    , currentCellIndex = old.currentCellIndex
    , cloneReference = old.cloneReference
    , deleteNotebookState = old.deleteNotebookState |> migrate_Types_DeleteNotebookState
    , showNotebooks = old.showNotebooks |> migrate_Types_ShowNotebooks
    , signupState = old.signupState |> migrate_Types_SignupState
    , currentUser = old.currentUser
    , inputUsername = old.inputUsername
    , inputSignupUsername = old.inputSignupUsername
    , inputEmail = old.inputEmail
    , inputRealname = old.inputRealname
    , inputPassword = old.inputPassword
    , inputPasswordAgain = old.inputPasswordAgain
    , inputTitle = old.inputTitle
    , windowWidth = old.windowWidth
    , windowHeight = old.windowHeight
    , popupState = old.popupState |> migrate_Types_PopupState
    , showEditor = old.showEditor
    }


migrate_LiveBook_DataSet_DataSetMetaData : Evergreen.V37.LiveBook.DataSet.DataSetMetaData -> Evergreen.V50.LiveBook.DataSet.DataSetMetaData
migrate_LiveBook_DataSet_DataSetMetaData old =
    old


migrate_LiveBook_Types_Book : Evergreen.V37.LiveBook.Types.Book -> Evergreen.V50.LiveBook.Types.Book
migrate_LiveBook_Types_Book old =
    { id = old.id
    , dirty = old.dirty
    , slug = old.slug
    , origin = old.origin
    , author = old.author
    , createdAt = old.createdAt
    , updatedAt = old.updatedAt
    , public = old.public
    , title = old.title
    , cells = old.cells |> List.map migrate_LiveBook_Types_Cell
    , currentIndex = old.currentIndex
    }


migrate_LiveBook_Types_Cell : Evergreen.V37.LiveBook.Types.Cell -> Evergreen.V50.LiveBook.Types.Cell
migrate_LiveBook_Types_Cell old =
    { index = old.index
    , text = old.text
    , value = old.value |> migrate_LiveBook_Types_CellValue
    , cellState = old.cellState |> migrate_LiveBook_Types_CellState
    , locked = old.locked
    }


migrate_LiveBook_Types_CellState : Evergreen.V37.LiveBook.Types.CellState -> Evergreen.V50.LiveBook.Types.CellState
migrate_LiveBook_Types_CellState old =
    case old of
        Evergreen.V37.LiveBook.Types.CSEdit ->
            Evergreen.V50.LiveBook.Types.CSEdit

        Evergreen.V37.LiveBook.Types.CSView ->
            Evergreen.V50.LiveBook.Types.CSView


migrate_LiveBook_Types_CellValue : Evergreen.V37.LiveBook.Types.CellValue -> Evergreen.V50.LiveBook.Types.CellValue
migrate_LiveBook_Types_CellValue old =
    case old of
        Evergreen.V37.LiveBook.Types.CVNone ->
            Evergreen.V50.LiveBook.Types.CVNone

        Evergreen.V37.LiveBook.Types.CVString p0 ->
            Evergreen.V50.LiveBook.Types.CVString p0

        Evergreen.V37.LiveBook.Types.CVVisual p0 p1 ->
            Evergreen.V50.LiveBook.Types.CVVisual (p0 |> migrate_LiveBook_Types_VisualType) p1


migrate_LiveBook_Types_VisualType : Evergreen.V37.LiveBook.Types.VisualType -> Evergreen.V50.LiveBook.Types.VisualType
migrate_LiveBook_Types_VisualType old =
    case old of
        Evergreen.V37.LiveBook.Types.VTChart ->
            Evergreen.V50.LiveBook.Types.VTChart

        Evergreen.V37.LiveBook.Types.VTImage ->
            Evergreen.V50.LiveBook.Types.VTImage


migrate_Types_AppMode : Evergreen.V37.Types.AppMode -> Evergreen.V50.Types.AppMode
migrate_Types_AppMode old =
    case old of
        Evergreen.V37.Types.AMWorking ->
            Evergreen.V50.Types.AMWorking

        Evergreen.V37.Types.AMEditTitle ->
            Evergreen.V50.Types.AMEditTitle


migrate_Types_AppState : Evergreen.V37.Types.AppState -> Evergreen.V50.Types.AppState
migrate_Types_AppState old =
    case old of
        Evergreen.V37.Types.Loading ->
            Evergreen.V50.Types.Loading

        Evergreen.V37.Types.Loaded ->
            Evergreen.V50.Types.Loaded


migrate_Types_DataSetDescription : Evergreen.V37.Types.DataSetDescription -> Evergreen.V50.Types.DataSetDescription
migrate_Types_DataSetDescription old =
    case old of
        Evergreen.V37.Types.PublicDatasets ->
            Evergreen.V50.Types.PublicDatasets

        Evergreen.V37.Types.UserDatasets p0 ->
            Evergreen.V50.Types.UserDatasets p0


migrate_Types_DeleteNotebookState : Evergreen.V37.Types.DeleteNotebookState -> Evergreen.V50.Types.DeleteNotebookState
migrate_Types_DeleteNotebookState old =
    case old of
        Evergreen.V37.Types.WaitingToDeleteNotebook ->
            Evergreen.V50.Types.WaitingToDeleteNotebook

        Evergreen.V37.Types.CanDeleteNotebook ->
            Evergreen.V50.Types.CanDeleteNotebook


migrate_Types_FrontendMsg : Evergreen.V37.Types.FrontendMsg -> Evergreen.V50.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V37.Types.UrlClicked p0 ->
            Evergreen.V50.Types.UrlClicked p0

        Evergreen.V37.Types.UrlChanged p0 ->
            Evergreen.V50.Types.UrlChanged p0

        Evergreen.V37.Types.NoOpFrontendMsg ->
            Evergreen.V50.Types.NoOpFrontendMsg

        Evergreen.V37.Types.FETick p0 ->
            Evergreen.V50.Types.FETick p0

        Evergreen.V37.Types.KeyboardMsg p0 ->
            Evergreen.V50.Types.KeyboardMsg p0

        Evergreen.V37.Types.StringDataRequested p0 p1 ->
            Evergreen.V50.Types.StringDataRequested p0 p1

        Evergreen.V37.Types.StringDataSelected p0 p1 p2 ->
            Evergreen.V50.Types.StringDataSelected p0 p1 p2

        Evergreen.V37.Types.StringDataLoaded p0 p1 p2 p3 ->
            Evergreen.V50.Types.StringDataLoaded p0 p1 p2 p3

        Evergreen.V37.Types.InputName p0 ->
            Evergreen.V50.Types.InputName p0

        Evergreen.V37.Types.InputDescription p0 ->
            Evergreen.V50.Types.InputDescription p0

        Evergreen.V37.Types.InputComments p0 ->
            Evergreen.V50.Types.InputComments p0

        Evergreen.V37.Types.InputData p0 ->
            Evergreen.V50.Types.InputData p0

        Evergreen.V37.Types.InputAuthor p0 ->
            Evergreen.V50.Types.InputAuthor p0

        Evergreen.V37.Types.AskToListDataSets p0 ->
            Evergreen.V50.Types.AskToListDataSets (p0 |> migrate_Types_DataSetDescription)

        Evergreen.V37.Types.AskToSaveDataSet p0 ->
            Evergreen.V50.Types.AskToSaveDataSet (p0 |> migrate_LiveBook_DataSet_DataSetMetaData)

        Evergreen.V37.Types.AskToCreateDataSet ->
            Evergreen.V50.Types.AskToCreateDataSet

        Evergreen.V37.Types.AskToDeleteDataSet p0 ->
            Evergreen.V50.Types.AskToDeleteDataSet (p0 |> migrate_LiveBook_DataSet_DataSetMetaData)

        Evergreen.V37.Types.ToggleCellLock p0 ->
            Evergreen.V50.Types.ToggleCellLock (p0 |> migrate_LiveBook_Types_Cell)

        Evergreen.V37.Types.NewCell p0 ->
            Evergreen.V50.Types.NewCell p0

        Evergreen.V37.Types.DeleteCell p0 ->
            Evergreen.V50.Types.DeleteCell p0

        Evergreen.V37.Types.EditCell p0 ->
            Evergreen.V50.Types.EditCell p0

        Evergreen.V37.Types.ClearCell p0 ->
            Evergreen.V50.Types.ClearCell p0

        Evergreen.V37.Types.EvalCell p0 ->
            Evergreen.V50.Types.EvalCell p0

        Evergreen.V37.Types.InputElmCode p0 p1 ->
            Evergreen.V50.Types.InputElmCode p0 p1

        Evergreen.V37.Types.UpdateNotebookTitle ->
            Evergreen.V50.Types.UpdateNotebookTitle

        Evergreen.V37.Types.NewNotebook ->
            Evergreen.V50.Types.NewNotebook

        Evergreen.V37.Types.ProposeDeletingNotebook ->
            Evergreen.V50.Types.ProposeDeletingNotebook

        Evergreen.V37.Types.CancelDeleteNotebook ->
            Evergreen.V50.Types.CancelDeleteNotebook

        Evergreen.V37.Types.ChangeAppMode p0 ->
            Evergreen.V50.Types.ChangeAppMode (p0 |> migrate_Types_AppMode)

        Evergreen.V37.Types.TogglePublic ->
            Evergreen.V50.Types.TogglePublic

        Evergreen.V37.Types.ClearNotebookValues ->
            Evergreen.V50.Types.ClearNotebookValues

        Evergreen.V37.Types.SetCurrentNotebook p0 ->
            Evergreen.V50.Types.SetCurrentNotebook (p0 |> migrate_LiveBook_Types_Book)

        Evergreen.V37.Types.CloneNotebook ->
            Evergreen.V50.Types.CloneNotebook

        Evergreen.V37.Types.PullNotebook ->
            Evergreen.V50.Types.PullNotebook

        Evergreen.V37.Types.SetShowNotebooksState p0 ->
            Evergreen.V50.Types.SetShowNotebooksState (p0 |> migrate_Types_ShowNotebooks)

        Evergreen.V37.Types.ChangePopup p0 ->
            Evergreen.V50.Types.ChangePopup (p0 |> migrate_Types_PopupState)

        Evergreen.V37.Types.GotViewport p0 ->
            Evergreen.V50.Types.GotViewport p0

        Evergreen.V37.Types.GotNewWindowDimensions p0 p1 ->
            Evergreen.V50.Types.GotNewWindowDimensions p0 p1

        Evergreen.V37.Types.SignUp ->
            Evergreen.V50.Types.SignUp

        Evergreen.V37.Types.SignIn ->
            Evergreen.V50.Types.SignIn

        Evergreen.V37.Types.SignOut ->
            Evergreen.V50.Types.SignOut

        Evergreen.V37.Types.SetSignupState p0 ->
            Evergreen.V50.Types.SetSignupState (p0 |> migrate_Types_SignupState)

        Evergreen.V37.Types.InputUsername p0 ->
            Evergreen.V50.Types.InputUsername p0

        Evergreen.V37.Types.InputSignupUsername p0 ->
            Evergreen.V50.Types.InputSignupUsername p0

        Evergreen.V37.Types.InputPassword p0 ->
            Evergreen.V50.Types.InputPassword p0

        Evergreen.V37.Types.InputPasswordAgain p0 ->
            Evergreen.V50.Types.InputPasswordAgain p0

        Evergreen.V37.Types.InputEmail p0 ->
            Evergreen.V50.Types.InputEmail p0

        Evergreen.V37.Types.InputTitle p0 ->
            Evergreen.V50.Types.InputTitle p0

        Evergreen.V37.Types.InputCloneReference p0 ->
            Evergreen.V50.Types.InputCloneReference p0

        Evergreen.V37.Types.AdminRunTask ->
            Evergreen.V50.Types.AdminRunTask

        Evergreen.V37.Types.GetUsers ->
            Evergreen.V50.Types.GetUsers


migrate_Types_Message : Evergreen.V37.Types.Message -> Evergreen.V50.Types.Message
migrate_Types_Message old =
    { txt = old.txt
    , status = old.status |> migrate_Types_MessageStatus
    }


migrate_Types_MessageStatus : Evergreen.V37.Types.MessageStatus -> Evergreen.V50.Types.MessageStatus
migrate_Types_MessageStatus old =
    case old of
        Evergreen.V37.Types.MSWhite ->
            Evergreen.V50.Types.MSWhite

        Evergreen.V37.Types.MSYellow ->
            Evergreen.V50.Types.MSYellow

        Evergreen.V37.Types.MSGreen ->
            Evergreen.V50.Types.MSGreen

        Evergreen.V37.Types.MSRed ->
            Evergreen.V50.Types.MSRed


migrate_Types_PopupState : Evergreen.V37.Types.PopupState -> Evergreen.V50.Types.PopupState
migrate_Types_PopupState old =
    case old of
        Evergreen.V37.Types.NoPopup ->
            Evergreen.V50.Types.NoPopup

        Evergreen.V37.Types.AdminPopup ->
            Evergreen.V50.Types.AdminPopup

        Evergreen.V37.Types.ManualPopup ->
            Evergreen.V50.Types.ManualPopup

        Evergreen.V37.Types.NewDataSetPopup ->
            Evergreen.V50.Types.NewDataSetPopup

        Evergreen.V37.Types.EditDataSetPopup p0 ->
            Evergreen.V50.Types.EditDataSetPopup (p0 |> migrate_LiveBook_DataSet_DataSetMetaData)

        Evergreen.V37.Types.SignUpPopup ->
            Evergreen.V50.Types.SignUpPopup

        Evergreen.V37.Types.NewNotebookPopup ->
            Evergreen.V50.Types.NewNotebookPopup

        Evergreen.V37.Types.ViewPublicDataSetsPopup ->
            Evergreen.V50.Types.ViewPublicDataSetsPopup

        Evergreen.V37.Types.ViewPrivateDataSetsPopup ->
            Evergreen.V50.Types.ViewPrivateDataSetsPopup


migrate_Types_ShowNotebooks : Evergreen.V37.Types.ShowNotebooks -> Evergreen.V50.Types.ShowNotebooks
migrate_Types_ShowNotebooks old =
    case old of
        Evergreen.V37.Types.ShowUserNotebooks ->
            Evergreen.V50.Types.ShowUserNotebooks

        Evergreen.V37.Types.ShowPublicNotebooks ->
            Evergreen.V50.Types.ShowPublicNotebooks


migrate_Types_SignupState : Evergreen.V37.Types.SignupState -> Evergreen.V50.Types.SignupState
migrate_Types_SignupState old =
    case old of
        Evergreen.V37.Types.ShowSignUpForm ->
            Evergreen.V50.Types.ShowSignUpForm

        Evergreen.V37.Types.HideSignUpForm ->
            Evergreen.V50.Types.HideSignUpForm
