module Evergreen.Migrate.V76 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Evergreen.V42.Types
import Evergreen.V76.Types
import Lamdera.Migrations exposing (..)
import List


frontendModel : Evergreen.V42.Types.FrontendModel -> ModelMigration Evergreen.V76.Types.FrontendModel Evergreen.V76.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V42.Types.BackendModel -> ModelMigration Evergreen.V76.Types.BackendModel Evergreen.V76.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V42.Types.FrontendMsg -> MsgMigration Evergreen.V76.Types.FrontendMsg Evergreen.V76.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V42.Types.ToBackend -> MsgMigration Evergreen.V76.Types.ToBackend Evergreen.V76.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V42.Types.BackendMsg -> MsgMigration Evergreen.V76.Types.BackendMsg Evergreen.V76.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V42.Types.ToFrontend -> MsgMigration Evergreen.V76.Types.ToFrontend Evergreen.V76.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V42.Types.FrontendModel -> Evergreen.V76.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , url = old.url
    , message = old.message
    , messages = old.messages |> List.map migrate_Types_Message
    , appState = old.appState |> migrate_Types_AppState
    , appMode = old.appMode |> migrate_Types_AppMode
    , currentTime = old.currentTime
    , pressedKeys = old.pressedKeys
    , users = old.users
    , stringData = Nothing
    , books = old.books |> List.map migrate_Types_Book
    , currentBook = old.currentBook |> migrate_Types_Book
    , cellContent = old.cellContent
    , currentCellIndex = old.currentCellIndex
    , cloneReference = old.cloneReference
    , deleteNotebookState = old.deleteNotebookState |> migrate_Types_DeleteNotebookState
    , showNotebooks = old.showNotebooks |> migrate_Types_ShowNotebooks
    , signupState = old.signupState |> migrate_Types_SignupState
    , currentUser = old.currentUser
    , inputUsername = old.inputUsername
    , inputSignupUsername = old.inputSignupUsername
    , inputEmail = old.inputEmail
    , inputRealname = old.inputRealname
    , inputPassword = old.inputPassword
    , inputPasswordAgain = old.inputPasswordAgain
    , inputTitle = old.inputTitle
    , windowWidth = old.windowWidth
    , windowHeight = old.windowHeight
    , popupState = old.popupState |> migrate_Types_PopupState
    , showEditor = old.showEditor
    }


migrate_Types_AppMode : Evergreen.V42.Types.AppMode -> Evergreen.V76.Types.AppMode
migrate_Types_AppMode old =
    case old of
        Evergreen.V42.Types.AMWorking ->
            Evergreen.V76.Types.AMWorking

        Evergreen.V42.Types.AMEditTitle ->
            Evergreen.V76.Types.AMEditTitle


migrate_Types_AppState : Evergreen.V42.Types.AppState -> Evergreen.V76.Types.AppState
migrate_Types_AppState old =
    case old of
        Evergreen.V42.Types.Loading ->
            Evergreen.V76.Types.Loading

        Evergreen.V42.Types.Loaded ->
            Evergreen.V76.Types.Loaded


migrate_Types_Book : Evergreen.V42.Types.Book -> Evergreen.V76.Types.Book
migrate_Types_Book old =
    { id = old.id
    , dirty = old.dirty
    , slug = old.slug
    , origin = old.origin
    , author = old.author
    , createdAt = old.createdAt
    , updatedAt = old.updatedAt
    , public = old.public
    , title = old.title
    , cells = old.cells |> List.map migrate_Types_Cell
    , currentIndex = old.currentIndex
    }


migrate_Types_Cell : Evergreen.V42.Types.Cell -> Evergreen.V76.Types.Cell
migrate_Types_Cell old =
    { index = old.index
    , text = old.text
    , value = old.value
    , cellState = old.cellState |> migrate_Types_CellState
    }


migrate_Types_CellState : Evergreen.V42.Types.CellState -> Evergreen.V76.Types.CellState
migrate_Types_CellState old =
    case old of
        Evergreen.V42.Types.CSEdit ->
            Evergreen.V76.Types.CSEdit

        Evergreen.V42.Types.CSView ->
            Evergreen.V76.Types.CSView


migrate_Types_DeleteNotebookState : Evergreen.V42.Types.DeleteNotebookState -> Evergreen.V76.Types.DeleteNotebookState
migrate_Types_DeleteNotebookState old =
    case old of
        Evergreen.V42.Types.WaitingToDeleteNotebook ->
            Evergreen.V76.Types.WaitingToDeleteNotebook

        Evergreen.V42.Types.CanDeleteNotebook ->
            Evergreen.V76.Types.CanDeleteNotebook


migrate_Types_FrontendMsg : Evergreen.V42.Types.FrontendMsg -> Evergreen.V76.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V42.Types.UrlClicked p0 ->
            Evergreen.V76.Types.UrlClicked p0

        Evergreen.V42.Types.UrlChanged p0 ->
            Evergreen.V76.Types.UrlChanged p0

        Evergreen.V42.Types.NoOpFrontendMsg ->
            Evergreen.V76.Types.NoOpFrontendMsg

        Evergreen.V42.Types.FETick p0 ->
            Evergreen.V76.Types.FETick p0

        Evergreen.V42.Types.KeyboardMsg p0 ->
            Evergreen.V76.Types.KeyboardMsg p0

        Evergreen.V42.Types.NewCell p0 ->
            Evergreen.V76.Types.NewCell p0

        Evergreen.V42.Types.DeleteCell p0 ->
            Evergreen.V76.Types.DeleteCell p0

        Evergreen.V42.Types.EditCell p0 ->
            Evergreen.V76.Types.EditCell p0

        Evergreen.V42.Types.ClearCell p0 ->
            Evergreen.V76.Types.ClearCell p0

        Evergreen.V42.Types.EvalCell p0 ->
            Evergreen.V76.Types.EvalCell p0

        Evergreen.V42.Types.InputElmCode p0 p1 ->
            Evergreen.V76.Types.InputElmCode p0 p1

        Evergreen.V42.Types.UpdateNotebookTitle ->
            Evergreen.V76.Types.UpdateNotebookTitle

        Evergreen.V42.Types.NewNotebook ->
            Evergreen.V76.Types.NewNotebook

        Evergreen.V42.Types.ProposeDeletingNotebook ->
            Evergreen.V76.Types.ProposeDeletingNotebook

        Evergreen.V42.Types.CancelDeleteNotebook ->
            Evergreen.V76.Types.CancelDeleteNotebook

        Evergreen.V42.Types.ChangeAppMode p0 ->
            Evergreen.V76.Types.ChangeAppMode (p0 |> migrate_Types_AppMode)

        Evergreen.V42.Types.TogglePublic ->
            Evergreen.V76.Types.TogglePublic

        Evergreen.V42.Types.SetCurrentNotebook p0 ->
            Evergreen.V76.Types.SetCurrentNotebook (p0 |> migrate_Types_Book)

        Evergreen.V42.Types.CloneNotebook ->
            Evergreen.V76.Types.CloneNotebook

        Evergreen.V42.Types.PullNotebook ->
            Evergreen.V76.Types.PullNotebook

        Evergreen.V42.Types.SetShowNotebooksState p0 ->
            Evergreen.V76.Types.SetShowNotebooksState (p0 |> migrate_Types_ShowNotebooks)

        Evergreen.V42.Types.ChangePopup p0 ->
            Evergreen.V76.Types.ChangePopup (p0 |> migrate_Types_PopupState)

        Evergreen.V42.Types.GotViewport p0 ->
            Evergreen.V76.Types.GotViewport p0

        Evergreen.V42.Types.GotNewWindowDimensions p0 p1 ->
            Evergreen.V76.Types.GotNewWindowDimensions p0 p1

        Evergreen.V42.Types.SignUp ->
            Evergreen.V76.Types.SignUp

        Evergreen.V42.Types.SignIn ->
            Evergreen.V76.Types.SignIn

        Evergreen.V42.Types.SignOut ->
            Evergreen.V76.Types.SignOut

        Evergreen.V42.Types.SetSignupState p0 ->
            Evergreen.V76.Types.SetSignupState (p0 |> migrate_Types_SignupState)

        Evergreen.V42.Types.InputUsername p0 ->
            Evergreen.V76.Types.InputUsername p0

        Evergreen.V42.Types.InputSignupUsername p0 ->
            Evergreen.V76.Types.InputSignupUsername p0

        Evergreen.V42.Types.InputPassword p0 ->
            Evergreen.V76.Types.InputPassword p0

        Evergreen.V42.Types.InputPasswordAgain p0 ->
            Evergreen.V76.Types.InputPasswordAgain p0

        Evergreen.V42.Types.InputEmail p0 ->
            Evergreen.V76.Types.InputEmail p0

        Evergreen.V42.Types.InputTitle p0 ->
            Evergreen.V76.Types.InputTitle p0

        Evergreen.V42.Types.InputCloneReference p0 ->
            Evergreen.V76.Types.InputCloneReference p0

        Evergreen.V42.Types.AdminRunTask ->
            Evergreen.V76.Types.AdminRunTask

        Evergreen.V42.Types.GetUsers ->
            Evergreen.V76.Types.GetUsers


migrate_Types_Message : Evergreen.V42.Types.Message -> Evergreen.V76.Types.Message
migrate_Types_Message old =
    { txt = old.txt
    , status = old.status |> migrate_Types_MessageStatus
    }


migrate_Types_MessageStatus : Evergreen.V42.Types.MessageStatus -> Evergreen.V76.Types.MessageStatus
migrate_Types_MessageStatus old =
    case old of
        Evergreen.V42.Types.MSWhite ->
            Evergreen.V76.Types.MSWhite

        Evergreen.V42.Types.MSYellow ->
            Evergreen.V76.Types.MSYellow

        Evergreen.V42.Types.MSGreen ->
            Evergreen.V76.Types.MSGreen

        Evergreen.V42.Types.MSRed ->
            Evergreen.V76.Types.MSRed


migrate_Types_PopupState : Evergreen.V42.Types.PopupState -> Evergreen.V76.Types.PopupState
migrate_Types_PopupState old =
    case old of
        Evergreen.V42.Types.NoPopup ->
            Evergreen.V76.Types.NoPopup

        Evergreen.V42.Types.AdminPopup ->
            Evergreen.V76.Types.AdminPopup

        Evergreen.V42.Types.ManualPopup ->
            Evergreen.V76.Types.ManualPopup

        Evergreen.V42.Types.SignUpPopup ->
            Evergreen.V76.Types.SignUpPopup

        Evergreen.V42.Types.NewNotebookPopup ->
            Evergreen.V76.Types.NewNotebookPopup


migrate_Types_ShowNotebooks : Evergreen.V42.Types.ShowNotebooks -> Evergreen.V76.Types.ShowNotebooks
migrate_Types_ShowNotebooks old =
    case old of
        Evergreen.V42.Types.ShowUserNotebooks ->
            Evergreen.V76.Types.ShowUserNotebooks

        Evergreen.V42.Types.ShowPublicNotebooks ->
            Evergreen.V76.Types.ShowPublicNotebooks


migrate_Types_SignupState : Evergreen.V42.Types.SignupState -> Evergreen.V76.Types.SignupState
migrate_Types_SignupState old =
    case old of
        Evergreen.V42.Types.ShowSignUpForm ->
            Evergreen.V76.Types.ShowSignUpForm

        Evergreen.V42.Types.HideSignUpForm ->
            Evergreen.V76.Types.HideSignUpForm
