module Evergreen.Migrate.V82 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Array
import Dict
import Evergreen.V81.Authentication
import Evergreen.V81.Credentials
import Evergreen.V81.FastDict
import Evergreen.V81.Internal
import Evergreen.V81.LiveBook.DataSet
import Evergreen.V81.LiveBook.Types
import Evergreen.V81.Types
import Evergreen.V81.User
import Evergreen.V81.Value
import Evergreen.V82.Authentication
import Evergreen.V82.Credentials
import Evergreen.V82.FastDict
import Evergreen.V82.Internal
import Evergreen.V82.LiveBook.DataSet
import Evergreen.V82.LiveBook.State
import Evergreen.V82.LiveBook.Types
import Evergreen.V82.Types
import Evergreen.V82.User
import Evergreen.V82.Value
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V81.Types.FrontendModel -> ModelMigration Evergreen.V82.Types.FrontendModel Evergreen.V82.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V81.Types.BackendModel -> ModelMigration Evergreen.V82.Types.BackendModel Evergreen.V82.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V81.Types.FrontendMsg -> MsgMigration Evergreen.V82.Types.FrontendMsg Evergreen.V82.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V81.Types.ToBackend -> MsgMigration Evergreen.V82.Types.ToBackend Evergreen.V82.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V81.Types.BackendMsg -> MsgMigration Evergreen.V82.Types.BackendMsg Evergreen.V82.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V81.Types.ToFrontend -> MsgMigration Evergreen.V82.Types.ToFrontend Evergreen.V82.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V81.Types.BackendModel -> Evergreen.V82.Types.BackendModel
migrate_Types_BackendModel old =
    { message = old.message
    , currentTime = old.currentTime
    , randomSeed = old.randomSeed
    , uuidCount = old.uuidCount
    , uuid = old.uuid
    , randomAtmosphericInt = old.randomAtmosphericInt
    , dataSetLibrary = old.dataSetLibrary
    , userToNoteBookDict = old.userToNoteBookDict |> migrate_Types_UserToNoteBookDict
    , slugDict = old.slugDict
    , authenticationDict = old.authenticationDict |> migrate_Authentication_AuthenticationDict
    }


migrate_Types_FrontendModel : Evergreen.V81.Types.FrontendModel -> Evergreen.V82.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , url = old.url
    , message = old.message
    , messages = old.messages |> List.map migrate_Types_Message
    , appState = old.appState |> migrate_Types_AppState
    , appMode = old.appMode |> migrate_Types_AppMode
    , currentTime = old.currentTime
    , tickCount = old.tickCount
    , clockState = old.clockState |> migrate_Types_ClockState
    , pressedKeys = old.pressedKeys
    , randomSeed = old.randomSeed
    , randomProbabilities = old.randomProbabilities
    , probabilityVectorLength = old.probabilityVectorLength
    , users = old.users
    , inputName = old.inputName
    , inputIdentifier = old.inputIdentifier
    , inputAuthor = old.inputAuthor
    , inputDescription = old.inputDescription
    , inputComments = old.inputComments
    , inputData = old.inputData
    , publicDataSetMetaDataList = old.publicDataSetMetaDataList
    , privateDataSetMetaDataList = old.privateDataSetMetaDataList
    , kvDict = old.kvDict
    , books = old.books |> List.map migrate_LiveBook_Types_Book
    , currentBook = old.currentBook |> migrate_LiveBook_Types_Book
    , cellContent = old.cellContent
    , currentCellIndex = old.currentCellIndex
    , cloneReference = old.cloneReference
    , deleteNotebookState = old.deleteNotebookState |> migrate_Types_DeleteNotebookState
    , showNotebooks = old.showNotebooks |> migrate_Types_ShowNotebooks
    , valueDict = old.valueDict |> Dict.map (\k -> migrate_Value_Value)
    , nextStateRecord = Nothing
    , state = initialState
    , signupState = old.signupState |> migrate_Types_SignupState
    , currentUser = old.currentUser
    , inputUsername = old.inputUsername
    , inputSignupUsername = old.inputSignupUsername
    , inputEmail = old.inputEmail
    , inputRealname = old.inputRealname
    , inputPassword = old.inputPassword
    , inputPasswordAgain = old.inputPasswordAgain
    , inputTitle = old.inputTitle
    , windowWidth = old.windowWidth
    , windowHeight = old.windowHeight
    , popupState = old.popupState |> migrate_Types_PopupState
    , showEditor = old.showEditor
    }


initialState : Evergreen.V82.LiveBook.State.MState
initialState =
    { value = Evergreen.V82.Value.Float 10
    , values = [ Evergreen.V82.Value.Float 10 ]
    , probabilities = []
    , ticks = 0
    , expression = "if state <= 0 then 0 else state + ds p0"
    , bindings = [ "ds p = if p < 0.5 then -1 else 1" ]
    }


migrate_Authentication_AuthenticationDict : Evergreen.V81.Authentication.AuthenticationDict -> Evergreen.V82.Authentication.AuthenticationDict
migrate_Authentication_AuthenticationDict old =
    old |> Dict.map (\k -> migrate_Authentication_UserData)


migrate_Authentication_UserData : Evergreen.V81.Authentication.UserData -> Evergreen.V82.Authentication.UserData
migrate_Authentication_UserData old =
    { user = old.user |> migrate_User_User
    , credentials = old.credentials |> migrate_Credentials_Credentials
    }


migrate_Credentials_Credentials : Evergreen.V81.Credentials.Credentials -> Evergreen.V82.Credentials.Credentials
migrate_Credentials_Credentials old =
    case old of
        Evergreen.V81.Credentials.V1 p0 p1 ->
            Evergreen.V82.Credentials.V1 p0 p1


migrate_FastDict_Dict : (k_old -> k_new) -> (v_old -> v_new) -> Evergreen.V81.FastDict.Dict k_old v_old -> Evergreen.V82.FastDict.Dict k_new v_new
migrate_FastDict_Dict migrate_k migrate_v old =
    old |> migrate_Internal_InternalDict migrate_k migrate_v


migrate_Internal_InnerDict : (k_old -> k_new) -> (v_old -> v_new) -> Evergreen.V81.Internal.InnerDict k_old v_old -> Evergreen.V82.Internal.InnerDict k_new v_new
migrate_Internal_InnerDict migrate_k migrate_v old =
    case old of
        Evergreen.V81.Internal.InnerNode p0 p1 p2 p3 p4 ->
            Evergreen.V82.Internal.InnerNode (p0 |> migrate_Internal_NColor)
                (p1 |> migrate_k)
                (p2 |> migrate_v)
                (p3 |> migrate_Internal_InnerDict migrate_k migrate_v)
                (p4 |> migrate_Internal_InnerDict migrate_k migrate_v)

        Evergreen.V81.Internal.Leaf ->
            Evergreen.V82.Internal.Leaf


migrate_Internal_InternalDict : (k_old -> k_new) -> (v_old -> v_new) -> Evergreen.V81.Internal.InternalDict k_old v_old -> Evergreen.V82.Internal.InternalDict k_new v_new
migrate_Internal_InternalDict migrate_k migrate_v old =
    case old of
        Evergreen.V81.Internal.Dict p0 p1 ->
            Evergreen.V82.Internal.Dict p0
                (p1 |> migrate_Internal_InnerDict migrate_k migrate_v)


migrate_Internal_NColor : Evergreen.V81.Internal.NColor -> Evergreen.V82.Internal.NColor
migrate_Internal_NColor old =
    case old of
        Evergreen.V81.Internal.Red ->
            Evergreen.V82.Internal.Red

        Evergreen.V81.Internal.Black ->
            Evergreen.V82.Internal.Black


migrate_LiveBook_DataSet_DataSet : Evergreen.V81.LiveBook.DataSet.DataSet -> Evergreen.V82.LiveBook.DataSet.DataSet
migrate_LiveBook_DataSet_DataSet old =
    old


migrate_LiveBook_DataSet_DataSetMetaData : Evergreen.V81.LiveBook.DataSet.DataSetMetaData -> Evergreen.V82.LiveBook.DataSet.DataSetMetaData
migrate_LiveBook_DataSet_DataSetMetaData old =
    old


migrate_LiveBook_Types_Book : Evergreen.V81.LiveBook.Types.Book -> Evergreen.V82.LiveBook.Types.Book
migrate_LiveBook_Types_Book old =
    { id = old.id
    , dirty = old.dirty
    , slug = old.slug
    , origin = old.origin
    , author = old.author
    , createdAt = old.createdAt
    , updatedAt = old.updatedAt
    , public = old.public
    , title = old.title
    , cells = old.cells |> List.map migrate_LiveBook_Types_Cell
    , currentIndex = old.currentIndex
    }


migrate_LiveBook_Types_Cell : Evergreen.V81.LiveBook.Types.Cell -> Evergreen.V82.LiveBook.Types.Cell
migrate_LiveBook_Types_Cell old =
    { index = old.index
    , text = old.text
    , bindings = old.bindings
    , expression = old.expression
    , value = old.value |> migrate_LiveBook_Types_CellValue
    , cellState = old.cellState |> migrate_LiveBook_Types_CellState
    , locked = old.locked
    }


migrate_LiveBook_Types_CellState : Evergreen.V81.LiveBook.Types.CellState -> Evergreen.V82.LiveBook.Types.CellState
migrate_LiveBook_Types_CellState old =
    case old of
        Evergreen.V81.LiveBook.Types.CSEdit ->
            Evergreen.V82.LiveBook.Types.CSEdit

        Evergreen.V81.LiveBook.Types.CSView ->
            Evergreen.V82.LiveBook.Types.CSView


migrate_LiveBook_Types_CellValue : Evergreen.V81.LiveBook.Types.CellValue -> Evergreen.V82.LiveBook.Types.CellValue
migrate_LiveBook_Types_CellValue old =
    case old of
        Evergreen.V81.LiveBook.Types.CVNone ->
            Evergreen.V82.LiveBook.Types.CVNone

        Evergreen.V81.LiveBook.Types.CVString p0 ->
            Evergreen.V82.LiveBook.Types.CVString p0

        Evergreen.V81.LiveBook.Types.CVVisual p0 p1 ->
            Evergreen.V82.LiveBook.Types.CVVisual (p0 |> migrate_LiveBook_Types_VisualType) p1


migrate_LiveBook_Types_VisualType : Evergreen.V81.LiveBook.Types.VisualType -> Evergreen.V82.LiveBook.Types.VisualType
migrate_LiveBook_Types_VisualType old =
    case old of
        Evergreen.V81.LiveBook.Types.VTChart ->
            Evergreen.V82.LiveBook.Types.VTChart

        Evergreen.V81.LiveBook.Types.VTSvg ->
            Evergreen.V82.LiveBook.Types.VTSvg

        Evergreen.V81.LiveBook.Types.VTImage ->
            Evergreen.V82.LiveBook.Types.VTImage

        Evergreen.V81.LiveBook.Types.VTPlot2D ->
            Evergreen.V82.LiveBook.Types.VTImage


migrate_Types_AppMode : Evergreen.V81.Types.AppMode -> Evergreen.V82.Types.AppMode
migrate_Types_AppMode old =
    case old of
        Evergreen.V81.Types.AMWorking ->
            Evergreen.V82.Types.AMWorking

        Evergreen.V81.Types.AMEditTitle ->
            Evergreen.V82.Types.AMEditTitle


migrate_Types_AppState : Evergreen.V81.Types.AppState -> Evergreen.V82.Types.AppState
migrate_Types_AppState old =
    case old of
        Evergreen.V81.Types.Loading ->
            Evergreen.V82.Types.Loading

        Evergreen.V81.Types.Loaded ->
            Evergreen.V82.Types.Loaded


migrate_Types_ClockState : Evergreen.V81.Types.ClockState -> Evergreen.V82.Types.ClockState
migrate_Types_ClockState old =
    case old of
        Evergreen.V81.Types.ClockRunning ->
            Evergreen.V82.Types.ClockRunning

        Evergreen.V81.Types.ClockStopped ->
            Evergreen.V82.Types.ClockStopped

        Evergreen.V81.Types.ClockPaused ->
            Evergreen.V82.Types.ClockPaused


migrate_Types_DataSetDescription : Evergreen.V81.Types.DataSetDescription -> Evergreen.V82.Types.DataSetDescription
migrate_Types_DataSetDescription old =
    case old of
        Evergreen.V81.Types.PublicDatasets ->
            Evergreen.V82.Types.PublicDatasets

        Evergreen.V81.Types.UserDatasets p0 ->
            Evergreen.V82.Types.UserDatasets p0


migrate_Types_DeleteNotebookState : Evergreen.V81.Types.DeleteNotebookState -> Evergreen.V82.Types.DeleteNotebookState
migrate_Types_DeleteNotebookState old =
    case old of
        Evergreen.V81.Types.WaitingToDeleteNotebook ->
            Evergreen.V82.Types.WaitingToDeleteNotebook

        Evergreen.V81.Types.CanDeleteNotebook ->
            Evergreen.V82.Types.CanDeleteNotebook


migrate_Types_FrontendMsg : Evergreen.V81.Types.FrontendMsg -> Evergreen.V82.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V81.Types.UrlClicked p0 ->
            Evergreen.V82.Types.UrlClicked p0

        Evergreen.V81.Types.UrlChanged p0 ->
            Evergreen.V82.Types.UrlChanged p0

        Evergreen.V81.Types.NoOpFrontendMsg ->
            Evergreen.V82.Types.NoOpFrontendMsg

        Evergreen.V81.Types.FETick p0 ->
            Evergreen.V82.Types.FETick p0

        Evergreen.V81.Types.FastTick p0 ->
            Evergreen.V82.Types.FastTick p0

        Evergreen.V81.Types.KeyboardMsg p0 ->
            Evergreen.V82.Types.KeyboardMsg p0

        Evergreen.V81.Types.GetRandomProbabilities p0 ->
            Evergreen.V82.Types.GetRandomProbabilities p0

        Evergreen.V81.Types.GotRandomProbabilities p0 ->
            Evergreen.V82.Types.GotRandomProbabilities p0

        Evergreen.V81.Types.StringDataRequested p0 p1 ->
            Evergreen.V82.Types.StringDataRequested p0 p1

        Evergreen.V81.Types.StringDataSelected p0 p1 p2 ->
            Evergreen.V82.Types.StringDataSelected p0 p1 p2

        Evergreen.V81.Types.StringDataLoaded p0 p1 p2 p3 ->
            Evergreen.V82.Types.StringDataLoaded p0 p1 p2 p3

        Evergreen.V81.Types.InputName p0 ->
            Evergreen.V82.Types.InputName p0

        Evergreen.V81.Types.InputIdentifier p0 ->
            Evergreen.V82.Types.InputIdentifier p0

        Evergreen.V81.Types.InputDescription p0 ->
            Evergreen.V82.Types.InputDescription p0

        Evergreen.V81.Types.InputComments p0 ->
            Evergreen.V82.Types.InputComments p0

        Evergreen.V81.Types.InputData p0 ->
            Evergreen.V82.Types.InputData p0

        Evergreen.V81.Types.InputAuthor p0 ->
            Evergreen.V82.Types.InputAuthor p0

        Evergreen.V81.Types.AskToListDataSets p0 ->
            Evergreen.V82.Types.AskToListDataSets (p0 |> migrate_Types_DataSetDescription)

        Evergreen.V81.Types.AskToSaveDataSet p0 ->
            Evergreen.V82.Types.AskToSaveDataSet (p0 |> migrate_LiveBook_DataSet_DataSetMetaData)

        Evergreen.V81.Types.AskToCreateDataSet ->
            Evergreen.V82.Types.AskToCreateDataSet

        Evergreen.V81.Types.AskToDeleteDataSet p0 ->
            Evergreen.V82.Types.AskToDeleteDataSet (p0 |> migrate_LiveBook_DataSet_DataSetMetaData)

        Evergreen.V81.Types.ToggleCellLock p0 ->
            Evergreen.V82.Types.ToggleCellLock (p0 |> migrate_LiveBook_Types_Cell)

        Evergreen.V81.Types.NewCell p0 ->
            Evergreen.V82.Types.NewCell p0

        Evergreen.V81.Types.DeleteCell p0 ->
            Evergreen.V82.Types.DeleteCell p0

        Evergreen.V81.Types.EditCell p0 ->
            Evergreen.V82.Types.EditCell p0

        Evergreen.V81.Types.ClearCell p0 ->
            Evergreen.V82.Types.ClearCell p0

        Evergreen.V81.Types.EvalCell p0 ->
            Evergreen.V82.Types.EvalCell p0

        Evergreen.V81.Types.InputElmCode p0 p1 ->
            Evergreen.V82.Types.InputElmCode p0 p1

        Evergreen.V81.Types.UpdateNotebookTitle ->
            Evergreen.V82.Types.UpdateNotebookTitle

        Evergreen.V81.Types.NewNotebook ->
            Evergreen.V82.Types.NewNotebook

        Evergreen.V81.Types.ProposeDeletingNotebook ->
            Evergreen.V82.Types.ProposeDeletingNotebook

        Evergreen.V81.Types.CancelDeleteNotebook ->
            Evergreen.V82.Types.CancelDeleteNotebook

        Evergreen.V81.Types.ChangeAppMode p0 ->
            Evergreen.V82.Types.ChangeAppMode (p0 |> migrate_Types_AppMode)

        Evergreen.V81.Types.SetClock p0 ->
            Evergreen.V82.Types.SetClock (p0 |> migrate_Types_ClockState)

        Evergreen.V81.Types.ResetClock ->
            Evergreen.V82.Types.ResetClock

        Evergreen.V81.Types.TogglePublic ->
            Evergreen.V82.Types.TogglePublic

        Evergreen.V81.Types.ClearNotebookValues ->
            Evergreen.V82.Types.ClearNotebookValues

        Evergreen.V81.Types.SetCurrentNotebook p0 ->
            Evergreen.V82.Types.SetCurrentNotebook (p0 |> migrate_LiveBook_Types_Book)

        Evergreen.V81.Types.CloneNotebook ->
            Evergreen.V82.Types.CloneNotebook

        Evergreen.V81.Types.PullNotebook ->
            Evergreen.V82.Types.PullNotebook

        Evergreen.V81.Types.SetShowNotebooksState p0 ->
            Evergreen.V82.Types.SetShowNotebooksState (p0 |> migrate_Types_ShowNotebooks)

        Evergreen.V81.Types.ChangePopup p0 ->
            Evergreen.V82.Types.ChangePopup (p0 |> migrate_Types_PopupState)

        Evergreen.V81.Types.GotViewport p0 ->
            Evergreen.V82.Types.GotViewport p0

        Evergreen.V81.Types.GotNewWindowDimensions p0 p1 ->
            Evergreen.V82.Types.GotNewWindowDimensions p0 p1

        Evergreen.V81.Types.SignUp ->
            Evergreen.V82.Types.SignUp

        Evergreen.V81.Types.SignIn ->
            Evergreen.V82.Types.SignIn

        Evergreen.V81.Types.SignOut ->
            Evergreen.V82.Types.SignOut

        Evergreen.V81.Types.SetSignupState p0 ->
            Evergreen.V82.Types.SetSignupState (p0 |> migrate_Types_SignupState)

        Evergreen.V81.Types.InputUsername p0 ->
            Evergreen.V82.Types.InputUsername p0

        Evergreen.V81.Types.InputSignupUsername p0 ->
            Evergreen.V82.Types.InputSignupUsername p0

        Evergreen.V81.Types.InputPassword p0 ->
            Evergreen.V82.Types.InputPassword p0

        Evergreen.V81.Types.InputPasswordAgain p0 ->
            Evergreen.V82.Types.InputPasswordAgain p0

        Evergreen.V81.Types.InputEmail p0 ->
            Evergreen.V82.Types.InputEmail p0

        Evergreen.V81.Types.InputTitle p0 ->
            Evergreen.V82.Types.InputTitle p0

        Evergreen.V81.Types.InputCloneReference p0 ->
            Evergreen.V82.Types.InputCloneReference p0

        Evergreen.V81.Types.AdminRunTask ->
            Evergreen.V82.Types.AdminRunTask

        Evergreen.V81.Types.GetUsers ->
            Evergreen.V82.Types.GetUsers


migrate_Types_Message : Evergreen.V81.Types.Message -> Evergreen.V82.Types.Message
migrate_Types_Message old =
    { txt = old.txt
    , status = old.status |> migrate_Types_MessageStatus
    }


migrate_Types_MessageStatus : Evergreen.V81.Types.MessageStatus -> Evergreen.V82.Types.MessageStatus
migrate_Types_MessageStatus old =
    case old of
        Evergreen.V81.Types.MSWhite ->
            Evergreen.V82.Types.MSWhite

        Evergreen.V81.Types.MSYellow ->
            Evergreen.V82.Types.MSYellow

        Evergreen.V81.Types.MSGreen ->
            Evergreen.V82.Types.MSGreen

        Evergreen.V81.Types.MSRed ->
            Evergreen.V82.Types.MSRed


migrate_Types_NoteBookDict : Evergreen.V81.Types.NoteBookDict -> Evergreen.V82.Types.NoteBookDict
migrate_Types_NoteBookDict old =
    old |> Dict.map (\k -> migrate_LiveBook_Types_Book)


migrate_Types_PopupState : Evergreen.V81.Types.PopupState -> Evergreen.V82.Types.PopupState
migrate_Types_PopupState old =
    case old of
        Evergreen.V81.Types.NoPopup ->
            Evergreen.V82.Types.NoPopup

        Evergreen.V81.Types.AdminPopup ->
            Evergreen.V82.Types.AdminPopup

        Evergreen.V81.Types.ManualPopup ->
            Evergreen.V82.Types.ManualPopup

        Evergreen.V81.Types.NewDataSetPopup ->
            Evergreen.V82.Types.NewDataSetPopup

        Evergreen.V81.Types.EditDataSetPopup p0 ->
            Evergreen.V82.Types.EditDataSetPopup (p0 |> migrate_LiveBook_DataSet_DataSetMetaData)

        Evergreen.V81.Types.SignUpPopup ->
            Evergreen.V82.Types.SignUpPopup

        Evergreen.V81.Types.NewNotebookPopup ->
            Evergreen.V82.Types.NewNotebookPopup

        Evergreen.V81.Types.ViewPublicDataSetsPopup ->
            Evergreen.V82.Types.ViewPublicDataSetsPopup

        Evergreen.V81.Types.ViewPrivateDataSetsPopup ->
            Evergreen.V82.Types.ViewPrivateDataSetsPopup


migrate_Types_ShowNotebooks : Evergreen.V81.Types.ShowNotebooks -> Evergreen.V82.Types.ShowNotebooks
migrate_Types_ShowNotebooks old =
    case old of
        Evergreen.V81.Types.ShowUserNotebooks ->
            Evergreen.V82.Types.ShowUserNotebooks

        Evergreen.V81.Types.ShowPublicNotebooks ->
            Evergreen.V82.Types.ShowPublicNotebooks


migrate_Types_SignupState : Evergreen.V81.Types.SignupState -> Evergreen.V82.Types.SignupState
migrate_Types_SignupState old =
    case old of
        Evergreen.V81.Types.ShowSignUpForm ->
            Evergreen.V82.Types.ShowSignUpForm

        Evergreen.V81.Types.HideSignUpForm ->
            Evergreen.V82.Types.HideSignUpForm


migrate_Types_ToBackend : Evergreen.V81.Types.ToBackend -> Evergreen.V82.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V81.Types.NoOpToBackend ->
            Evergreen.V82.Types.NoOpToBackend

        Evergreen.V81.Types.GetRandomSeed ->
            Evergreen.V82.Types.GetRandomSeed

        Evergreen.V81.Types.RunTask ->
            Evergreen.V82.Types.RunTask

        Evergreen.V81.Types.SendUsers ->
            Evergreen.V82.Types.SendUsers

        Evergreen.V81.Types.DeleteDataSet p0 ->
            Evergreen.V82.Types.DeleteDataSet (p0 |> migrate_LiveBook_DataSet_DataSetMetaData)

        Evergreen.V81.Types.SaveDataSet p0 ->
            Evergreen.V82.Types.SaveDataSet (p0 |> migrate_LiveBook_DataSet_DataSetMetaData)

        Evergreen.V81.Types.GetListOfDataSets p0 ->
            Evergreen.V82.Types.GetListOfDataSets (p0 |> migrate_Types_DataSetDescription)

        Evergreen.V81.Types.CreateDataSet p0 ->
            Evergreen.V82.Types.CreateDataSet (p0 |> migrate_LiveBook_DataSet_DataSet)

        Evergreen.V81.Types.GetData p0 p1 p2 ->
            Evergreen.V82.Types.GetData p0 p1 p2

        Evergreen.V81.Types.GetDataSetForDownload p0 ->
            Evergreen.V82.Types.GetDataSetForDownload p0

        Evergreen.V81.Types.CreateNotebook p0 p1 ->
            Evergreen.V82.Types.CreateNotebook p0 p1

        Evergreen.V81.Types.SaveNotebook p0 ->
            Evergreen.V82.Types.SaveNotebook (p0 |> migrate_LiveBook_Types_Book)

        Evergreen.V81.Types.DeleteNotebook p0 ->
            Evergreen.V82.Types.DeleteNotebook (p0 |> migrate_LiveBook_Types_Book)

        Evergreen.V81.Types.GetClonedNotebook p0 p1 ->
            Evergreen.V82.Types.GetClonedNotebook p0 p1

        Evergreen.V81.Types.GetPulledNotebook p0 p1 p2 p3 ->
            Evergreen.V82.Types.GetPulledNotebook p0 p1 p2 p3

        Evergreen.V81.Types.UpdateSlugDict p0 ->
            Evergreen.V82.Types.UpdateSlugDict (p0 |> migrate_LiveBook_Types_Book)

        Evergreen.V81.Types.GetUsersNotebooks p0 ->
            Evergreen.V82.Types.GetUsersNotebooks p0

        Evergreen.V81.Types.GetPublicNotebooks p0 ->
            Evergreen.V82.Types.GetPublicNotebooks p0

        Evergreen.V81.Types.SignUpBE p0 p1 p2 ->
            Evergreen.V82.Types.SignUpBE p0 p1 p2

        Evergreen.V81.Types.SignInBEDev ->
            Evergreen.V82.Types.SignInBEDev

        Evergreen.V81.Types.SignInBE p0 p1 ->
            Evergreen.V82.Types.SignInBE p0 p1

        Evergreen.V81.Types.SignOutBE p0 ->
            Evergreen.V82.Types.SignOutBE p0

        Evergreen.V81.Types.UpdateUserWith p0 ->
            Evergreen.V82.Types.UpdateUserWith (p0 |> migrate_User_User)


migrate_Types_ToFrontend : Evergreen.V81.Types.ToFrontend -> Evergreen.V82.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V81.Types.NoOpToFrontend ->
            Evergreen.V82.Types.NoOpToFrontend

        Evergreen.V81.Types.MessageReceived p0 ->
            Evergreen.V82.Types.MessageReceived (p0 |> migrate_Types_Message)

        Evergreen.V81.Types.GotRandomSeed p0 ->
            Evergreen.V82.Types.GotRandomSeed p0

        Evergreen.V81.Types.GotUsers p0 ->
            Evergreen.V82.Types.GotUsers p0

        Evergreen.V81.Types.GotListOfPublicDataSets p0 ->
            Evergreen.V82.Types.GotListOfPublicDataSets p0

        Evergreen.V81.Types.GotListOfPrivateDataSets p0 ->
            Evergreen.V82.Types.GotListOfPrivateDataSets p0

        Evergreen.V81.Types.GotData p0 p1 p2 ->
            Evergreen.V82.Types.GotData p0 p1 (p2 |> migrate_LiveBook_DataSet_DataSet)

        Evergreen.V81.Types.GotDataForDownload p0 ->
            Evergreen.V82.Types.GotDataForDownload (p0 |> migrate_LiveBook_DataSet_DataSet)

        Evergreen.V81.Types.GotNotebook p0 ->
            Evergreen.V82.Types.GotNotebook (p0 |> migrate_LiveBook_Types_Book)

        Evergreen.V81.Types.GotNotebooks p0 ->
            Evergreen.V82.Types.GotNotebooks (p0 |> List.map migrate_LiveBook_Types_Book)

        Evergreen.V81.Types.SendMessage p0 ->
            Evergreen.V82.Types.SendMessage p0

        Evergreen.V81.Types.UserSignedIn p0 p1 ->
            Evergreen.V82.Types.UserSignedIn (p0 |> migrate_User_User) p1

        Evergreen.V81.Types.SendUser p0 ->
            Evergreen.V82.Types.SendUser (p0 |> migrate_User_User)


migrate_Types_UserToNoteBookDict : Evergreen.V81.Types.UserToNoteBookDict -> Evergreen.V82.Types.UserToNoteBookDict
migrate_Types_UserToNoteBookDict old =
    old |> Dict.map (\k -> migrate_Types_NoteBookDict)


migrate_User_User : Evergreen.V81.User.User -> Evergreen.V82.User.User
migrate_User_User old =
    old


migrate_Value_Env : Evergreen.V81.Value.Env -> Evergreen.V82.Value.Env
migrate_Value_Env old =
    { currentModule = old.currentModule
    , functions = old.functions |> migrate_FastDict_Dict identity (migrate_FastDict_Dict identity identity)
    , values = old.values |> migrate_Value_EnvValues
    , callStack = old.callStack
    }


migrate_Value_EnvValues : Evergreen.V81.Value.EnvValues -> Evergreen.V82.Value.EnvValues
migrate_Value_EnvValues old =
    old |> migrate_FastDict_Dict identity migrate_Value_Value


migrate_Value_Value : Evergreen.V81.Value.Value -> Evergreen.V82.Value.Value
migrate_Value_Value old =
    case old of
        Evergreen.V81.Value.String p0 ->
            Evergreen.V82.Value.String p0

        Evergreen.V81.Value.Int p0 ->
            Evergreen.V82.Value.Int p0

        Evergreen.V81.Value.Float p0 ->
            Evergreen.V82.Value.Float p0

        Evergreen.V81.Value.Char p0 ->
            Evergreen.V82.Value.Char p0

        Evergreen.V81.Value.Bool p0 ->
            Evergreen.V82.Value.Bool p0

        Evergreen.V81.Value.Unit ->
            Evergreen.V82.Value.Unit

        Evergreen.V81.Value.Tuple p0 p1 ->
            Evergreen.V82.Value.Tuple (p0 |> migrate_Value_Value)
                (p1 |> migrate_Value_Value)

        Evergreen.V81.Value.Triple p0 p1 p2 ->
            Evergreen.V82.Value.Triple (p0 |> migrate_Value_Value)
                (p1 |> migrate_Value_Value)
                (p2 |> migrate_Value_Value)

        Evergreen.V81.Value.Record p0 ->
            Evergreen.V82.Value.Record (p0 |> migrate_FastDict_Dict identity migrate_Value_Value)

        Evergreen.V81.Value.Custom p0 p1 ->
            Evergreen.V82.Value.Custom p0 (p1 |> List.map migrate_Value_Value)

        Evergreen.V81.Value.PartiallyApplied p0 p1 p2 p3 p4 ->
            Evergreen.V82.Value.PartiallyApplied (p0 |> migrate_Value_Env)
                (p1 |> List.map migrate_Value_Value)
                p2
                p3
                p4

        Evergreen.V81.Value.JsArray p0 ->
            Evergreen.V82.Value.JsArray (p0 |> Array.map migrate_Value_Value)

        Evergreen.V81.Value.List p0 ->
            Evergreen.V82.Value.List (p0 |> List.map migrate_Value_Value)
